"""
Additional domain definitions for synthetic 250-table database generator.
Part 3: Healthcare, Education, Project Management, IT/Infrastructure, Marketing
"""

from typing import Dict, List, Any

DOMAINS_MORE: Dict[str, Dict[str, Any]] = {
    # ═══════════════════════════════════════════════════════════════════════════
    # HEALTHCARE (25 tables)
    # ═══════════════════════════════════════════════════════════════════════════
    "healthcare": {
        "description": "Healthcare and Medical Records",
        "tables": [
            {
                "name": "patients",
                "columns": [
                    {"name": "patient_id", "type": "SERIAL", "primary_key": True},
                    {"name": "mrn", "type": "VARCHAR(50)", "unique": True},
                    {"name": "first_name", "type": "VARCHAR(100)", "not_null": True},
                    {"name": "last_name", "type": "VARCHAR(100)", "not_null": True},
                    {"name": "date_of_birth", "type": "DATE", "not_null": True},
                    {"name": "gender", "type": "VARCHAR(10)"},
                    {"name": "ssn_last4", "type": "VARCHAR(4)"},
                    {"name": "email", "type": "VARCHAR(255)"},
                    {"name": "phone", "type": "VARCHAR(20)"},
                    {"name": "address", "type": "TEXT"},
                    {"name": "emergency_contact_name", "type": "VARCHAR(200)"},
                    {"name": "emergency_contact_phone", "type": "VARCHAR(20)"},
                    {"name": "primary_physician_id", "type": "INTEGER", "fk": "physicians.physician_id"},
                    {"name": "insurance_id", "type": "INTEGER", "fk": "insurance_policies.insurance_id"},
                    {"name": "blood_type", "type": "VARCHAR(10)"},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                ],
            },
            {
                "name": "physicians",
                "columns": [
                    {"name": "physician_id", "type": "SERIAL", "primary_key": True},
                    {"name": "npi", "type": "VARCHAR(20)", "unique": True},
                    {"name": "first_name", "type": "VARCHAR(100)", "not_null": True},
                    {"name": "last_name", "type": "VARCHAR(100)", "not_null": True},
                    {"name": "specialty", "type": "VARCHAR(100)"},
                    {"name": "department_id", "type": "INTEGER", "fk": "medical_departments.department_id"},
                    {"name": "email", "type": "VARCHAR(255)"},
                    {"name": "phone", "type": "VARCHAR(20)"},
                    {"name": "license_number", "type": "VARCHAR(50)"},
                    {"name": "license_state", "type": "VARCHAR(2)"},
                    {"name": "hire_date", "type": "DATE"},
                    {"name": "is_accepting_patients", "type": "BOOLEAN", "default": "true"},
                ],
            },
            {
                "name": "medical_departments",
                "columns": [
                    {"name": "department_id", "type": "SERIAL", "primary_key": True},
                    {"name": "department_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "department_code", "type": "VARCHAR(20)", "unique": True},
                    {"name": "location", "type": "VARCHAR(200)"},
                    {"name": "phone", "type": "VARCHAR(20)"},
                    {"name": "head_physician_id", "type": "INTEGER"},
                ],
            },
            {
                "name": "appointments",
                "columns": [
                    {"name": "appointment_id", "type": "SERIAL", "primary_key": True},
                    {"name": "patient_id", "type": "INTEGER", "not_null": True, "fk": "patients.patient_id"},
                    {"name": "physician_id", "type": "INTEGER", "not_null": True, "fk": "physicians.physician_id"},
                    {"name": "appointment_date", "type": "TIMESTAMP", "not_null": True},
                    {"name": "duration_minutes", "type": "INTEGER", "default": "30"},
                    {"name": "appointment_type", "type": "VARCHAR(50)"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'scheduled'"},
                    {"name": "reason", "type": "TEXT"},
                    {"name": "notes", "type": "TEXT"},
                    {"name": "room_number", "type": "VARCHAR(20)"},
                    {"name": "checked_in_at", "type": "TIMESTAMP"},
                ],
            },
            {
                "name": "encounters",
                "columns": [
                    {"name": "encounter_id", "type": "SERIAL", "primary_key": True},
                    {"name": "patient_id", "type": "INTEGER", "not_null": True, "fk": "patients.patient_id"},
                    {"name": "physician_id", "type": "INTEGER", "not_null": True, "fk": "physicians.physician_id"},
                    {"name": "appointment_id", "type": "INTEGER", "fk": "appointments.appointment_id"},
                    {"name": "encounter_date", "type": "TIMESTAMP", "not_null": True},
                    {"name": "encounter_type", "type": "VARCHAR(50)"},
                    {"name": "chief_complaint", "type": "TEXT"},
                    {"name": "notes", "type": "TEXT"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'in_progress'"},
                ],
            },
            {
                "name": "diagnoses",
                "columns": [
                    {"name": "diagnosis_id", "type": "SERIAL", "primary_key": True},
                    {"name": "encounter_id", "type": "INTEGER", "not_null": True, "fk": "encounters.encounter_id"},
                    {"name": "icd10_code", "type": "VARCHAR(20)"},
                    {"name": "diagnosis_description", "type": "TEXT"},
                    {"name": "diagnosis_date", "type": "DATE"},
                    {"name": "is_primary", "type": "BOOLEAN", "default": "false"},
                    {"name": "severity", "type": "VARCHAR(50)"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'active'"},
                ],
            },
            {
                "name": "prescriptions",
                "columns": [
                    {"name": "prescription_id", "type": "SERIAL", "primary_key": True},
                    {"name": "patient_id", "type": "INTEGER", "not_null": True, "fk": "patients.patient_id"},
                    {"name": "physician_id", "type": "INTEGER", "not_null": True, "fk": "physicians.physician_id"},
                    {"name": "encounter_id", "type": "INTEGER", "fk": "encounters.encounter_id"},
                    {"name": "medication_id", "type": "INTEGER", "fk": "medications.medication_id"},
                    {"name": "dosage", "type": "VARCHAR(100)"},
                    {"name": "frequency", "type": "VARCHAR(100)"},
                    {"name": "quantity", "type": "INTEGER"},
                    {"name": "refills", "type": "INTEGER", "default": "0"},
                    {"name": "start_date", "type": "DATE"},
                    {"name": "end_date", "type": "DATE"},
                    {"name": "instructions", "type": "TEXT"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'active'"},
                ],
            },
            {
                "name": "medications",
                "columns": [
                    {"name": "medication_id", "type": "SERIAL", "primary_key": True},
                    {"name": "ndc_code", "type": "VARCHAR(20)"},
                    {"name": "medication_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "generic_name", "type": "VARCHAR(200)"},
                    {"name": "drug_class", "type": "VARCHAR(100)"},
                    {"name": "form", "type": "VARCHAR(50)"},
                    {"name": "strength", "type": "VARCHAR(100)"},
                    {"name": "manufacturer", "type": "VARCHAR(200)"},
                    {"name": "is_controlled", "type": "BOOLEAN", "default": "false"},
                ],
            },
            {
                "name": "allergies",
                "columns": [
                    {"name": "allergy_id", "type": "SERIAL", "primary_key": True},
                    {"name": "patient_id", "type": "INTEGER", "not_null": True, "fk": "patients.patient_id"},
                    {"name": "allergen", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "allergy_type", "type": "VARCHAR(50)"},
                    {"name": "reaction", "type": "TEXT"},
                    {"name": "severity", "type": "VARCHAR(50)"},
                    {"name": "onset_date", "type": "DATE"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'active'"},
                ],
            },
            {
                "name": "lab_orders",
                "columns": [
                    {"name": "order_id", "type": "SERIAL", "primary_key": True},
                    {"name": "patient_id", "type": "INTEGER", "not_null": True, "fk": "patients.patient_id"},
                    {"name": "physician_id", "type": "INTEGER", "not_null": True, "fk": "physicians.physician_id"},
                    {"name": "encounter_id", "type": "INTEGER", "fk": "encounters.encounter_id"},
                    {"name": "order_date", "type": "TIMESTAMP", "not_null": True},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'ordered'"},
                    {"name": "priority", "type": "VARCHAR(20)"},
                    {"name": "notes", "type": "TEXT"},
                ],
            },
            {
                "name": "lab_tests",
                "columns": [
                    {"name": "test_id", "type": "SERIAL", "primary_key": True},
                    {"name": "test_code", "type": "VARCHAR(50)", "unique": True},
                    {"name": "test_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "category", "type": "VARCHAR(100)"},
                    {"name": "specimen_type", "type": "VARCHAR(100)"},
                    {"name": "normal_range", "type": "VARCHAR(200)"},
                    {"name": "unit", "type": "VARCHAR(50)"},
                ],
            },
            {
                "name": "lab_results",
                "columns": [
                    {"name": "result_id", "type": "SERIAL", "primary_key": True},
                    {"name": "order_id", "type": "INTEGER", "not_null": True, "fk": "lab_orders.order_id"},
                    {"name": "test_id", "type": "INTEGER", "not_null": True, "fk": "lab_tests.test_id"},
                    {"name": "result_value", "type": "VARCHAR(200)"},
                    {"name": "result_unit", "type": "VARCHAR(50)"},
                    {"name": "reference_range", "type": "VARCHAR(200)"},
                    {"name": "abnormal_flag", "type": "VARCHAR(10)"},
                    {"name": "collected_date", "type": "TIMESTAMP"},
                    {"name": "resulted_date", "type": "TIMESTAMP"},
                    {"name": "status", "type": "VARCHAR(50)"},
                ],
            },
            {
                "name": "vital_signs",
                "columns": [
                    {"name": "vital_id", "type": "SERIAL", "primary_key": True},
                    {"name": "patient_id", "type": "INTEGER", "not_null": True, "fk": "patients.patient_id"},
                    {"name": "encounter_id", "type": "INTEGER", "fk": "encounters.encounter_id"},
                    {"name": "recorded_at", "type": "TIMESTAMP", "not_null": True},
                    {"name": "temperature_f", "type": "DECIMAL(5,2)"},
                    {"name": "blood_pressure_systolic", "type": "INTEGER"},
                    {"name": "blood_pressure_diastolic", "type": "INTEGER"},
                    {"name": "heart_rate", "type": "INTEGER"},
                    {"name": "respiratory_rate", "type": "INTEGER"},
                    {"name": "oxygen_saturation", "type": "DECIMAL(5,2)"},
                    {"name": "weight_kg", "type": "DECIMAL(6,2)"},
                    {"name": "height_cm", "type": "DECIMAL(5,1)"},
                    {"name": "bmi", "type": "DECIMAL(5,2)"},
                    {"name": "recorded_by", "type": "INTEGER"},
                ],
            },
            {
                "name": "immunizations",
                "columns": [
                    {"name": "immunization_id", "type": "SERIAL", "primary_key": True},
                    {"name": "patient_id", "type": "INTEGER", "not_null": True, "fk": "patients.patient_id"},
                    {"name": "vaccine_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "cvx_code", "type": "VARCHAR(20)"},
                    {"name": "administration_date", "type": "DATE", "not_null": True},
                    {"name": "lot_number", "type": "VARCHAR(50)"},
                    {"name": "expiration_date", "type": "DATE"},
                    {"name": "site", "type": "VARCHAR(100)"},
                    {"name": "dose_number", "type": "INTEGER"},
                    {"name": "administered_by", "type": "INTEGER"},
                ],
            },
            {
                "name": "insurance_policies",
                "columns": [
                    {"name": "insurance_id", "type": "SERIAL", "primary_key": True},
                    {"name": "patient_id", "type": "INTEGER", "not_null": True, "fk": "patients.patient_id"},
                    {"name": "payer_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "policy_number", "type": "VARCHAR(100)"},
                    {"name": "group_number", "type": "VARCHAR(100)"},
                    {"name": "subscriber_name", "type": "VARCHAR(200)"},
                    {"name": "relationship_to_subscriber", "type": "VARCHAR(50)"},
                    {"name": "coverage_type", "type": "VARCHAR(50)"},
                    {"name": "effective_date", "type": "DATE"},
                    {"name": "termination_date", "type": "DATE"},
                    {"name": "is_primary", "type": "BOOLEAN", "default": "true"},
                ],
            },
            {
                "name": "medical_claims",
                "columns": [
                    {"name": "claim_id", "type": "SERIAL", "primary_key": True},
                    {"name": "claim_number", "type": "VARCHAR(50)", "unique": True},
                    {"name": "patient_id", "type": "INTEGER", "not_null": True, "fk": "patients.patient_id"},
                    {"name": "encounter_id", "type": "INTEGER", "fk": "encounters.encounter_id"},
                    {"name": "insurance_id", "type": "INTEGER", "fk": "insurance_policies.insurance_id"},
                    {"name": "service_date", "type": "DATE", "not_null": True},
                    {"name": "submitted_date", "type": "DATE"},
                    {"name": "total_charges", "type": "DECIMAL(15,2)"},
                    {"name": "allowed_amount", "type": "DECIMAL(15,2)"},
                    {"name": "paid_amount", "type": "DECIMAL(15,2)"},
                    {"name": "patient_responsibility", "type": "DECIMAL(15,2)"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'pending'"},
                ],
            },
            {
                "name": "claim_lines",
                "columns": [
                    {"name": "claim_line_id", "type": "SERIAL", "primary_key": True},
                    {"name": "claim_id", "type": "INTEGER", "not_null": True, "fk": "medical_claims.claim_id"},
                    {"name": "procedure_code", "type": "VARCHAR(20)"},
                    {"name": "modifier", "type": "VARCHAR(20)"},
                    {"name": "diagnosis_pointer", "type": "VARCHAR(20)"},
                    {"name": "units", "type": "INTEGER", "default": "1"},
                    {"name": "charge_amount", "type": "DECIMAL(15,2)"},
                    {"name": "allowed_amount", "type": "DECIMAL(15,2)"},
                ],
            },
            {
                "name": "procedures",
                "columns": [
                    {"name": "procedure_id", "type": "SERIAL", "primary_key": True},
                    {"name": "patient_id", "type": "INTEGER", "not_null": True, "fk": "patients.patient_id"},
                    {"name": "physician_id", "type": "INTEGER", "fk": "physicians.physician_id"},
                    {"name": "encounter_id", "type": "INTEGER", "fk": "encounters.encounter_id"},
                    {"name": "cpt_code", "type": "VARCHAR(20)"},
                    {"name": "procedure_name", "type": "VARCHAR(500)"},
                    {"name": "procedure_date", "type": "TIMESTAMP"},
                    {"name": "notes", "type": "TEXT"},
                    {"name": "status", "type": "VARCHAR(50)"},
                ],
            },
            {
                "name": "referrals",
                "columns": [
                    {"name": "referral_id", "type": "SERIAL", "primary_key": True},
                    {"name": "patient_id", "type": "INTEGER", "not_null": True, "fk": "patients.patient_id"},
                    {"name": "referring_physician_id", "type": "INTEGER", "fk": "physicians.physician_id"},
                    {"name": "referred_to_physician_id", "type": "INTEGER", "fk": "physicians.physician_id"},
                    {"name": "referral_date", "type": "DATE", "not_null": True},
                    {"name": "reason", "type": "TEXT"},
                    {"name": "urgency", "type": "VARCHAR(50)"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'pending'"},
                    {"name": "authorization_number", "type": "VARCHAR(100)"},
                ],
            },
            {
                "name": "medical_history",
                "columns": [
                    {"name": "history_id", "type": "SERIAL", "primary_key": True},
                    {"name": "patient_id", "type": "INTEGER", "not_null": True, "fk": "patients.patient_id"},
                    {"name": "condition", "type": "VARCHAR(500)", "not_null": True},
                    {"name": "icd10_code", "type": "VARCHAR(20)"},
                    {"name": "onset_date", "type": "DATE"},
                    {"name": "resolution_date", "type": "DATE"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'active'"},
                    {"name": "notes", "type": "TEXT"},
                ],
            },
            {
                "name": "family_history",
                "columns": [
                    {"name": "family_history_id", "type": "SERIAL", "primary_key": True},
                    {"name": "patient_id", "type": "INTEGER", "not_null": True, "fk": "patients.patient_id"},
                    {"name": "relationship", "type": "VARCHAR(50)", "not_null": True},
                    {"name": "condition", "type": "VARCHAR(500)", "not_null": True},
                    {"name": "age_at_onset", "type": "INTEGER"},
                    {"name": "notes", "type": "TEXT"},
                ],
            },
            {
                "name": "care_plans",
                "columns": [
                    {"name": "plan_id", "type": "SERIAL", "primary_key": True},
                    {"name": "patient_id", "type": "INTEGER", "not_null": True, "fk": "patients.patient_id"},
                    {"name": "physician_id", "type": "INTEGER", "fk": "physicians.physician_id"},
                    {"name": "plan_name", "type": "VARCHAR(200)"},
                    {"name": "start_date", "type": "DATE"},
                    {"name": "end_date", "type": "DATE"},
                    {"name": "goals", "type": "TEXT"},
                    {"name": "interventions", "type": "TEXT"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'active'"},
                ],
            },
            {
                "name": "care_team_members",
                "columns": [
                    {"name": "team_member_id", "type": "SERIAL", "primary_key": True},
                    {"name": "patient_id", "type": "INTEGER", "not_null": True, "fk": "patients.patient_id"},
                    {"name": "physician_id", "type": "INTEGER", "fk": "physicians.physician_id"},
                    {"name": "role", "type": "VARCHAR(100)"},
                    {"name": "start_date", "type": "DATE"},
                    {"name": "end_date", "type": "DATE"},
                    {"name": "is_primary", "type": "BOOLEAN", "default": "false"},
                ],
            },
            {
                "name": "patient_consents",
                "columns": [
                    {"name": "consent_id", "type": "SERIAL", "primary_key": True},
                    {"name": "patient_id", "type": "INTEGER", "not_null": True, "fk": "patients.patient_id"},
                    {"name": "consent_type", "type": "VARCHAR(100)", "not_null": True},
                    {"name": "consent_date", "type": "DATE", "not_null": True},
                    {"name": "expiration_date", "type": "DATE"},
                    {"name": "granted_by", "type": "VARCHAR(200)"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'active'"},
                    {"name": "document_url", "type": "VARCHAR(500)"},
                ],
            },
        ],
    },
    # ═══════════════════════════════════════════════════════════════════════════
    # PROJECT MANAGEMENT (20 tables)
    # ═══════════════════════════════════════════════════════════════════════════
    "projects": {
        "description": "Project Management and Task Tracking",
        "tables": [
            {
                "name": "project_portfolio",
                "columns": [
                    {"name": "portfolio_id", "type": "SERIAL", "primary_key": True},
                    {"name": "portfolio_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "description", "type": "TEXT"},
                    {"name": "owner_id", "type": "INTEGER"},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                ],
            },
            {
                "name": "pm_projects",
                "columns": [
                    {"name": "project_id", "type": "SERIAL", "primary_key": True},
                    {"name": "project_code", "type": "VARCHAR(50)", "unique": True},
                    {"name": "project_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "portfolio_id", "type": "INTEGER", "fk": "project_portfolio.portfolio_id"},
                    {"name": "description", "type": "TEXT"},
                    {"name": "start_date", "type": "DATE"},
                    {"name": "target_end_date", "type": "DATE"},
                    {"name": "actual_end_date", "type": "DATE"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'planning'"},
                    {"name": "priority", "type": "VARCHAR(20)"},
                    {"name": "project_manager_id", "type": "INTEGER"},
                    {"name": "budget", "type": "DECIMAL(15,2)"},
                    {"name": "actual_cost", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "percent_complete", "type": "INTEGER", "default": "0"},
                ],
            },
            {
                "name": "project_phases",
                "columns": [
                    {"name": "phase_id", "type": "SERIAL", "primary_key": True},
                    {"name": "project_id", "type": "INTEGER", "not_null": True, "fk": "pm_projects.project_id"},
                    {"name": "phase_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "phase_order", "type": "INTEGER"},
                    {"name": "start_date", "type": "DATE"},
                    {"name": "end_date", "type": "DATE"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'not_started'"},
                ],
            },
            {
                "name": "milestones",
                "columns": [
                    {"name": "milestone_id", "type": "SERIAL", "primary_key": True},
                    {"name": "project_id", "type": "INTEGER", "not_null": True, "fk": "pm_projects.project_id"},
                    {"name": "phase_id", "type": "INTEGER", "fk": "project_phases.phase_id"},
                    {"name": "milestone_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "due_date", "type": "DATE"},
                    {"name": "completed_date", "type": "DATE"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'pending'"},
                    {"name": "description", "type": "TEXT"},
                ],
            },
            {
                "name": "pm_tasks",
                "columns": [
                    {"name": "task_id", "type": "SERIAL", "primary_key": True},
                    {"name": "project_id", "type": "INTEGER", "not_null": True, "fk": "pm_projects.project_id"},
                    {"name": "phase_id", "type": "INTEGER", "fk": "project_phases.phase_id"},
                    {"name": "milestone_id", "type": "INTEGER", "fk": "milestones.milestone_id"},
                    {"name": "parent_task_id", "type": "INTEGER", "fk": "pm_tasks.task_id"},
                    {"name": "task_name", "type": "VARCHAR(500)", "not_null": True},
                    {"name": "description", "type": "TEXT"},
                    {"name": "assigned_to", "type": "INTEGER"},
                    {"name": "start_date", "type": "DATE"},
                    {"name": "due_date", "type": "DATE"},
                    {"name": "completed_date", "type": "DATE"},
                    {"name": "estimated_hours", "type": "DECIMAL(8,2)"},
                    {"name": "actual_hours", "type": "DECIMAL(8,2)", "default": "0"},
                    {"name": "priority", "type": "VARCHAR(20)"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'todo'"},
                ],
            },
            {
                "name": "task_dependencies",
                "columns": [
                    {"name": "dependency_id", "type": "SERIAL", "primary_key": True},
                    {"name": "task_id", "type": "INTEGER", "not_null": True, "fk": "pm_tasks.task_id"},
                    {"name": "depends_on_task_id", "type": "INTEGER", "not_null": True, "fk": "pm_tasks.task_id"},
                    {"name": "dependency_type", "type": "VARCHAR(50)", "default": "'finish_to_start'"},
                    {"name": "lag_days", "type": "INTEGER", "default": "0"},
                ],
            },
            {
                "name": "task_assignments",
                "columns": [
                    {"name": "assignment_id", "type": "SERIAL", "primary_key": True},
                    {"name": "task_id", "type": "INTEGER", "not_null": True, "fk": "pm_tasks.task_id"},
                    {"name": "user_id", "type": "INTEGER", "not_null": True},
                    {"name": "role", "type": "VARCHAR(100)"},
                    {"name": "allocation_percentage", "type": "INTEGER", "default": "100"},
                ],
            },
            {
                "name": "time_entries",
                "columns": [
                    {"name": "entry_id", "type": "SERIAL", "primary_key": True},
                    {"name": "task_id", "type": "INTEGER", "not_null": True, "fk": "pm_tasks.task_id"},
                    {"name": "user_id", "type": "INTEGER", "not_null": True},
                    {"name": "entry_date", "type": "DATE", "not_null": True},
                    {"name": "hours_worked", "type": "DECIMAL(5,2)", "not_null": True},
                    {"name": "description", "type": "TEXT"},
                    {"name": "is_billable", "type": "BOOLEAN", "default": "true"},
                    {"name": "billing_rate", "type": "DECIMAL(10,2)"},
                ],
            },
            {
                "name": "project_members",
                "columns": [
                    {"name": "member_id", "type": "SERIAL", "primary_key": True},
                    {"name": "project_id", "type": "INTEGER", "not_null": True, "fk": "pm_projects.project_id"},
                    {"name": "user_id", "type": "INTEGER", "not_null": True},
                    {"name": "role", "type": "VARCHAR(100)"},
                    {"name": "join_date", "type": "DATE"},
                    {"name": "leave_date", "type": "DATE"},
                    {"name": "hourly_rate", "type": "DECIMAL(10,2)"},
                ],
            },
            {
                "name": "project_risks",
                "columns": [
                    {"name": "risk_id", "type": "SERIAL", "primary_key": True},
                    {"name": "project_id", "type": "INTEGER", "not_null": True, "fk": "pm_projects.project_id"},
                    {"name": "risk_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "description", "type": "TEXT"},
                    {"name": "probability", "type": "VARCHAR(20)"},
                    {"name": "impact", "type": "VARCHAR(20)"},
                    {"name": "risk_score", "type": "INTEGER"},
                    {"name": "mitigation_plan", "type": "TEXT"},
                    {"name": "owner_id", "type": "INTEGER"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'identified'"},
                ],
            },
            {
                "name": "project_issues",
                "columns": [
                    {"name": "issue_id", "type": "SERIAL", "primary_key": True},
                    {"name": "project_id", "type": "INTEGER", "not_null": True, "fk": "pm_projects.project_id"},
                    {"name": "issue_title", "type": "VARCHAR(500)", "not_null": True},
                    {"name": "description", "type": "TEXT"},
                    {"name": "priority", "type": "VARCHAR(20)"},
                    {"name": "severity", "type": "VARCHAR(20)"},
                    {"name": "assigned_to", "type": "INTEGER"},
                    {"name": "reported_by", "type": "INTEGER"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'open'"},
                    {"name": "resolution", "type": "TEXT"},
                ],
            },
            {
                "name": "project_documents",
                "columns": [
                    {"name": "document_id", "type": "SERIAL", "primary_key": True},
                    {"name": "project_id", "type": "INTEGER", "not_null": True, "fk": "pm_projects.project_id"},
                    {"name": "document_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "document_type", "type": "VARCHAR(50)"},
                    {"name": "file_path", "type": "VARCHAR(500)"},
                    {"name": "version", "type": "VARCHAR(20)"},
                    {"name": "uploaded_by", "type": "INTEGER"},
                    {"name": "upload_date", "type": "TIMESTAMP"},
                    {"name": "description", "type": "TEXT"},
                ],
            },
            {
                "name": "project_comments",
                "columns": [
                    {"name": "comment_id", "type": "SERIAL", "primary_key": True},
                    {"name": "project_id", "type": "INTEGER", "fk": "pm_projects.project_id"},
                    {"name": "task_id", "type": "INTEGER", "fk": "pm_tasks.task_id"},
                    {"name": "parent_comment_id", "type": "INTEGER", "fk": "project_comments.comment_id"},
                    {"name": "comment_text", "type": "TEXT", "not_null": True},
                    {"name": "author_id", "type": "INTEGER"},
                ],
            },
            {
                "name": "sprints",
                "columns": [
                    {"name": "sprint_id", "type": "SERIAL", "primary_key": True},
                    {"name": "project_id", "type": "INTEGER", "not_null": True, "fk": "pm_projects.project_id"},
                    {"name": "sprint_name", "type": "VARCHAR(100)", "not_null": True},
                    {"name": "sprint_number", "type": "INTEGER"},
                    {"name": "start_date", "type": "DATE"},
                    {"name": "end_date", "type": "DATE"},
                    {"name": "goal", "type": "TEXT"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'planning'"},
                    {"name": "velocity", "type": "INTEGER"},
                ],
            },
            {
                "name": "sprint_tasks",
                "columns": [
                    {"name": "sprint_task_id", "type": "SERIAL", "primary_key": True},
                    {"name": "sprint_id", "type": "INTEGER", "not_null": True, "fk": "sprints.sprint_id"},
                    {"name": "task_id", "type": "INTEGER", "not_null": True, "fk": "pm_tasks.task_id"},
                    {"name": "story_points", "type": "INTEGER"},
                ],
            },
            {
                "name": "resource_calendar",
                "columns": [
                    {"name": "calendar_id", "type": "SERIAL", "primary_key": True},
                    {"name": "user_id", "type": "INTEGER", "not_null": True},
                    {"name": "date", "type": "DATE", "not_null": True},
                    {"name": "available_hours", "type": "DECIMAL(4,2)", "default": "8"},
                    {"name": "is_working_day", "type": "BOOLEAN", "default": "true"},
                    {"name": "notes", "type": "VARCHAR(500)"},
                ],
            },
            {
                "name": "project_budgets",
                "columns": [
                    {"name": "budget_id", "type": "SERIAL", "primary_key": True},
                    {"name": "project_id", "type": "INTEGER", "not_null": True, "fk": "pm_projects.project_id"},
                    {"name": "category", "type": "VARCHAR(100)"},
                    {"name": "budgeted_amount", "type": "DECIMAL(15,2)", "not_null": True},
                    {"name": "actual_amount", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "variance", "type": "DECIMAL(15,2)"},
                ],
            },
            {
                "name": "change_requests",
                "columns": [
                    {"name": "request_id", "type": "SERIAL", "primary_key": True},
                    {"name": "project_id", "type": "INTEGER", "not_null": True, "fk": "pm_projects.project_id"},
                    {"name": "request_title", "type": "VARCHAR(500)", "not_null": True},
                    {"name": "description", "type": "TEXT"},
                    {"name": "impact_analysis", "type": "TEXT"},
                    {"name": "requested_by", "type": "INTEGER"},
                    {"name": "request_date", "type": "DATE"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'submitted'"},
                    {"name": "approved_by", "type": "INTEGER"},
                    {"name": "approval_date", "type": "DATE"},
                ],
            },
            {
                "name": "project_status_reports",
                "columns": [
                    {"name": "report_id", "type": "SERIAL", "primary_key": True},
                    {"name": "project_id", "type": "INTEGER", "not_null": True, "fk": "pm_projects.project_id"},
                    {"name": "report_date", "type": "DATE", "not_null": True},
                    {"name": "overall_status", "type": "VARCHAR(50)"},
                    {"name": "schedule_status", "type": "VARCHAR(50)"},
                    {"name": "budget_status", "type": "VARCHAR(50)"},
                    {"name": "accomplishments", "type": "TEXT"},
                    {"name": "upcoming_tasks", "type": "TEXT"},
                    {"name": "issues_risks", "type": "TEXT"},
                    {"name": "submitted_by", "type": "INTEGER"},
                ],
            },
            {
                "name": "lessons_learned",
                "columns": [
                    {"name": "lesson_id", "type": "SERIAL", "primary_key": True},
                    {"name": "project_id", "type": "INTEGER", "not_null": True, "fk": "pm_projects.project_id"},
                    {"name": "lesson_title", "type": "VARCHAR(500)", "not_null": True},
                    {"name": "category", "type": "VARCHAR(100)"},
                    {"name": "description", "type": "TEXT"},
                    {"name": "recommendation", "type": "TEXT"},
                    {"name": "recorded_by", "type": "INTEGER"},
                    {"name": "record_date", "type": "DATE"},
                ],
            },
        ],
    },
    # ═══════════════════════════════════════════════════════════════════════════
    # MARKETING (25 tables)
    # ═══════════════════════════════════════════════════════════════════════════
    "marketing": {
        "description": "Marketing and Digital Analytics",
        "tables": [
            {
                "name": "marketing_campaigns",
                "columns": [
                    {"name": "campaign_id", "type": "SERIAL", "primary_key": True},
                    {"name": "campaign_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "campaign_type", "type": "VARCHAR(50)"},
                    {"name": "channel", "type": "VARCHAR(50)"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'draft'"},
                    {"name": "start_date", "type": "DATE"},
                    {"name": "end_date", "type": "DATE"},
                    {"name": "budget", "type": "DECIMAL(15,2)"},
                    {"name": "actual_spend", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "target_audience", "type": "TEXT"},
                    {"name": "goals", "type": "TEXT"},
                    {"name": "owner_id", "type": "INTEGER"},
                ],
            },
            {
                "name": "email_campaigns",
                "columns": [
                    {"name": "email_campaign_id", "type": "SERIAL", "primary_key": True},
                    {"name": "campaign_id", "type": "INTEGER", "fk": "marketing_campaigns.campaign_id"},
                    {"name": "subject_line", "type": "VARCHAR(500)", "not_null": True},
                    {"name": "from_name", "type": "VARCHAR(200)"},
                    {"name": "from_email", "type": "VARCHAR(255)"},
                    {"name": "reply_to", "type": "VARCHAR(255)"},
                    {"name": "template_id", "type": "INTEGER", "fk": "email_templates.template_id"},
                    {"name": "scheduled_date", "type": "TIMESTAMP"},
                    {"name": "sent_date", "type": "TIMESTAMP"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'draft'"},
                ],
            },
            {
                "name": "email_templates",
                "columns": [
                    {"name": "template_id", "type": "SERIAL", "primary_key": True},
                    {"name": "template_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "subject", "type": "VARCHAR(500)"},
                    {"name": "html_content", "type": "TEXT"},
                    {"name": "text_content", "type": "TEXT"},
                    {"name": "category", "type": "VARCHAR(100)"},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                ],
            },
            {
                "name": "email_sends",
                "columns": [
                    {"name": "send_id", "type": "SERIAL", "primary_key": True},
                    {"name": "email_campaign_id", "type": "INTEGER", "not_null": True, "fk": "email_campaigns.email_campaign_id"},
                    {"name": "recipient_email", "type": "VARCHAR(255)", "not_null": True},
                    {"name": "contact_id", "type": "INTEGER"},
                    {"name": "sent_at", "type": "TIMESTAMP"},
                    {"name": "delivered_at", "type": "TIMESTAMP"},
                    {"name": "opened_at", "type": "TIMESTAMP"},
                    {"name": "clicked_at", "type": "TIMESTAMP"},
                    {"name": "bounced", "type": "BOOLEAN", "default": "false"},
                    {"name": "bounce_type", "type": "VARCHAR(50)"},
                    {"name": "unsubscribed", "type": "BOOLEAN", "default": "false"},
                ],
            },
            {
                "name": "email_clicks",
                "columns": [
                    {"name": "click_id", "type": "SERIAL", "primary_key": True},
                    {"name": "send_id", "type": "INTEGER", "not_null": True, "fk": "email_sends.send_id"},
                    {"name": "link_url", "type": "VARCHAR(1000)"},
                    {"name": "clicked_at", "type": "TIMESTAMP"},
                    {"name": "user_agent", "type": "VARCHAR(500)"},
                    {"name": "ip_address", "type": "VARCHAR(50)"},
                ],
            },
            {
                "name": "mailing_lists",
                "columns": [
                    {"name": "list_id", "type": "SERIAL", "primary_key": True},
                    {"name": "list_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "description", "type": "TEXT"},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                    {"name": "subscriber_count", "type": "INTEGER", "default": "0"},
                ],
            },
            {
                "name": "list_subscribers",
                "columns": [
                    {"name": "subscriber_id", "type": "SERIAL", "primary_key": True},
                    {"name": "list_id", "type": "INTEGER", "not_null": True, "fk": "mailing_lists.list_id"},
                    {"name": "email", "type": "VARCHAR(255)", "not_null": True},
                    {"name": "first_name", "type": "VARCHAR(100)"},
                    {"name": "last_name", "type": "VARCHAR(100)"},
                    {"name": "subscribed_at", "type": "TIMESTAMP"},
                    {"name": "unsubscribed_at", "type": "TIMESTAMP"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'active'"},
                    {"name": "source", "type": "VARCHAR(100)"},
                ],
            },
            {
                "name": "landing_pages",
                "columns": [
                    {"name": "page_id", "type": "SERIAL", "primary_key": True},
                    {"name": "campaign_id", "type": "INTEGER", "fk": "marketing_campaigns.campaign_id"},
                    {"name": "page_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "url_slug", "type": "VARCHAR(200)", "unique": True},
                    {"name": "html_content", "type": "TEXT"},
                    {"name": "meta_title", "type": "VARCHAR(200)"},
                    {"name": "meta_description", "type": "TEXT"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'draft'"},
                    {"name": "published_at", "type": "TIMESTAMP"},
                ],
            },
            {
                "name": "landing_page_conversions",
                "columns": [
                    {"name": "conversion_id", "type": "SERIAL", "primary_key": True},
                    {"name": "page_id", "type": "INTEGER", "not_null": True, "fk": "landing_pages.page_id"},
                    {"name": "visitor_id", "type": "VARCHAR(100)"},
                    {"name": "converted_at", "type": "TIMESTAMP"},
                    {"name": "conversion_type", "type": "VARCHAR(100)"},
                    {"name": "conversion_value", "type": "DECIMAL(15,2)"},
                    {"name": "source", "type": "VARCHAR(200)"},
                    {"name": "medium", "type": "VARCHAR(100)"},
                    {"name": "campaign", "type": "VARCHAR(200)"},
                ],
            },
            {
                "name": "web_analytics_sessions",
                "columns": [
                    {"name": "session_id", "type": "SERIAL", "primary_key": True},
                    {"name": "visitor_id", "type": "VARCHAR(100)"},
                    {"name": "session_start", "type": "TIMESTAMP", "not_null": True},
                    {"name": "session_end", "type": "TIMESTAMP"},
                    {"name": "duration_seconds", "type": "INTEGER"},
                    {"name": "page_views", "type": "INTEGER", "default": "0"},
                    {"name": "source", "type": "VARCHAR(200)"},
                    {"name": "medium", "type": "VARCHAR(100)"},
                    {"name": "campaign", "type": "VARCHAR(200)"},
                    {"name": "landing_page", "type": "VARCHAR(500)"},
                    {"name": "exit_page", "type": "VARCHAR(500)"},
                    {"name": "device_type", "type": "VARCHAR(50)"},
                    {"name": "browser", "type": "VARCHAR(100)"},
                    {"name": "country", "type": "VARCHAR(100)"},
                ],
            },
            {
                "name": "web_analytics_pageviews",
                "columns": [
                    {"name": "pageview_id", "type": "SERIAL", "primary_key": True},
                    {"name": "session_id", "type": "INTEGER", "not_null": True, "fk": "web_analytics_sessions.session_id"},
                    {"name": "page_url", "type": "VARCHAR(500)"},
                    {"name": "page_title", "type": "VARCHAR(500)"},
                    {"name": "timestamp", "type": "TIMESTAMP"},
                    {"name": "time_on_page_seconds", "type": "INTEGER"},
                    {"name": "referrer", "type": "VARCHAR(500)"},
                ],
            },
            {
                "name": "web_events",
                "columns": [
                    {"name": "event_id", "type": "SERIAL", "primary_key": True},
                    {"name": "session_id", "type": "INTEGER", "fk": "web_analytics_sessions.session_id"},
                    {"name": "visitor_id", "type": "VARCHAR(100)"},
                    {"name": "event_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "event_category", "type": "VARCHAR(100)"},
                    {"name": "event_action", "type": "VARCHAR(100)"},
                    {"name": "event_label", "type": "VARCHAR(500)"},
                    {"name": "event_value", "type": "DECIMAL(15,2)"},
                    {"name": "timestamp", "type": "TIMESTAMP"},
                    {"name": "page_url", "type": "VARCHAR(500)"},
                ],
            },
            {
                "name": "social_accounts",
                "columns": [
                    {"name": "account_id", "type": "SERIAL", "primary_key": True},
                    {"name": "platform", "type": "VARCHAR(50)", "not_null": True},
                    {"name": "account_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "account_handle", "type": "VARCHAR(100)"},
                    {"name": "account_url", "type": "VARCHAR(500)"},
                    {"name": "followers_count", "type": "INTEGER", "default": "0"},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                ],
            },
            {
                "name": "social_posts",
                "columns": [
                    {"name": "post_id", "type": "SERIAL", "primary_key": True},
                    {"name": "account_id", "type": "INTEGER", "not_null": True, "fk": "social_accounts.account_id"},
                    {"name": "campaign_id", "type": "INTEGER", "fk": "marketing_campaigns.campaign_id"},
                    {"name": "content", "type": "TEXT"},
                    {"name": "media_url", "type": "VARCHAR(500)"},
                    {"name": "scheduled_at", "type": "TIMESTAMP"},
                    {"name": "published_at", "type": "TIMESTAMP"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'draft'"},
                    {"name": "platform_post_id", "type": "VARCHAR(200)"},
                ],
            },
            {
                "name": "social_metrics",
                "columns": [
                    {"name": "metric_id", "type": "SERIAL", "primary_key": True},
                    {"name": "post_id", "type": "INTEGER", "not_null": True, "fk": "social_posts.post_id"},
                    {"name": "recorded_at", "type": "TIMESTAMP"},
                    {"name": "impressions", "type": "INTEGER", "default": "0"},
                    {"name": "reach", "type": "INTEGER", "default": "0"},
                    {"name": "likes", "type": "INTEGER", "default": "0"},
                    {"name": "comments", "type": "INTEGER", "default": "0"},
                    {"name": "shares", "type": "INTEGER", "default": "0"},
                    {"name": "clicks", "type": "INTEGER", "default": "0"},
                    {"name": "engagement_rate", "type": "DECIMAL(5,4)"},
                ],
            },
            {
                "name": "ad_campaigns",
                "columns": [
                    {"name": "ad_campaign_id", "type": "SERIAL", "primary_key": True},
                    {"name": "campaign_id", "type": "INTEGER", "fk": "marketing_campaigns.campaign_id"},
                    {"name": "platform", "type": "VARCHAR(50)", "not_null": True},
                    {"name": "ad_campaign_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "objective", "type": "VARCHAR(100)"},
                    {"name": "budget", "type": "DECIMAL(15,2)"},
                    {"name": "daily_budget", "type": "DECIMAL(15,2)"},
                    {"name": "bid_strategy", "type": "VARCHAR(100)"},
                    {"name": "start_date", "type": "DATE"},
                    {"name": "end_date", "type": "DATE"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'paused'"},
                ],
            },
            {
                "name": "ad_groups",
                "columns": [
                    {"name": "ad_group_id", "type": "SERIAL", "primary_key": True},
                    {"name": "ad_campaign_id", "type": "INTEGER", "not_null": True, "fk": "ad_campaigns.ad_campaign_id"},
                    {"name": "ad_group_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "targeting", "type": "JSONB"},
                    {"name": "bid_amount", "type": "DECIMAL(10,2)"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'active'"},
                ],
            },
            {
                "name": "ads",
                "columns": [
                    {"name": "ad_id", "type": "SERIAL", "primary_key": True},
                    {"name": "ad_group_id", "type": "INTEGER", "not_null": True, "fk": "ad_groups.ad_group_id"},
                    {"name": "ad_name", "type": "VARCHAR(200)"},
                    {"name": "ad_type", "type": "VARCHAR(50)"},
                    {"name": "headline", "type": "VARCHAR(500)"},
                    {"name": "description", "type": "TEXT"},
                    {"name": "display_url", "type": "VARCHAR(500)"},
                    {"name": "final_url", "type": "VARCHAR(500)"},
                    {"name": "image_url", "type": "VARCHAR(500)"},
                    {"name": "video_url", "type": "VARCHAR(500)"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'active'"},
                ],
            },
            {
                "name": "ad_performance",
                "columns": [
                    {"name": "performance_id", "type": "SERIAL", "primary_key": True},
                    {"name": "ad_id", "type": "INTEGER", "not_null": True, "fk": "ads.ad_id"},
                    {"name": "date", "type": "DATE", "not_null": True},
                    {"name": "impressions", "type": "INTEGER", "default": "0"},
                    {"name": "clicks", "type": "INTEGER", "default": "0"},
                    {"name": "conversions", "type": "INTEGER", "default": "0"},
                    {"name": "spend", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "cpc", "type": "DECIMAL(10,4)"},
                    {"name": "cpm", "type": "DECIMAL(10,4)"},
                    {"name": "ctr", "type": "DECIMAL(6,4)"},
                    {"name": "conversion_rate", "type": "DECIMAL(6,4)"},
                ],
            },
            {
                "name": "keywords",
                "columns": [
                    {"name": "keyword_id", "type": "SERIAL", "primary_key": True},
                    {"name": "ad_group_id", "type": "INTEGER", "fk": "ad_groups.ad_group_id"},
                    {"name": "keyword", "type": "VARCHAR(500)", "not_null": True},
                    {"name": "match_type", "type": "VARCHAR(50)"},
                    {"name": "bid_amount", "type": "DECIMAL(10,2)"},
                    {"name": "quality_score", "type": "INTEGER"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'active'"},
                ],
            },
            {
                "name": "keyword_performance",
                "columns": [
                    {"name": "kw_perf_id", "type": "SERIAL", "primary_key": True},
                    {"name": "keyword_id", "type": "INTEGER", "not_null": True, "fk": "keywords.keyword_id"},
                    {"name": "date", "type": "DATE", "not_null": True},
                    {"name": "impressions", "type": "INTEGER", "default": "0"},
                    {"name": "clicks", "type": "INTEGER", "default": "0"},
                    {"name": "conversions", "type": "INTEGER", "default": "0"},
                    {"name": "spend", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "avg_position", "type": "DECIMAL(4,2)"},
                ],
            },
            {
                "name": "content_pieces",
                "columns": [
                    {"name": "content_id", "type": "SERIAL", "primary_key": True},
                    {"name": "title", "type": "VARCHAR(500)", "not_null": True},
                    {"name": "content_type", "type": "VARCHAR(50)"},
                    {"name": "body", "type": "TEXT"},
                    {"name": "author_id", "type": "INTEGER"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'draft'"},
                    {"name": "published_at", "type": "TIMESTAMP"},
                    {"name": "url", "type": "VARCHAR(500)"},
                    {"name": "featured_image", "type": "VARCHAR(500)"},
                    {"name": "seo_title", "type": "VARCHAR(200)"},
                    {"name": "seo_description", "type": "TEXT"},
                ],
            },
            {
                "name": "content_categories",
                "columns": [
                    {"name": "category_id", "type": "SERIAL", "primary_key": True},
                    {"name": "category_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "slug", "type": "VARCHAR(200)", "unique": True},
                    {"name": "parent_id", "type": "INTEGER", "fk": "content_categories.category_id"},
                ],
            },
            {
                "name": "content_category_map",
                "columns": [
                    {"name": "map_id", "type": "SERIAL", "primary_key": True},
                    {"name": "content_id", "type": "INTEGER", "not_null": True, "fk": "content_pieces.content_id"},
                    {"name": "category_id", "type": "INTEGER", "not_null": True, "fk": "content_categories.category_id"},
                ],
            },
            {
                "name": "utm_tracking",
                "columns": [
                    {"name": "tracking_id", "type": "SERIAL", "primary_key": True},
                    {"name": "campaign_id", "type": "INTEGER", "fk": "marketing_campaigns.campaign_id"},
                    {"name": "utm_source", "type": "VARCHAR(200)"},
                    {"name": "utm_medium", "type": "VARCHAR(100)"},
                    {"name": "utm_campaign", "type": "VARCHAR(200)"},
                    {"name": "utm_term", "type": "VARCHAR(500)"},
                    {"name": "utm_content", "type": "VARCHAR(200)"},
                    {"name": "destination_url", "type": "VARCHAR(500)"},
                    {"name": "short_url", "type": "VARCHAR(200)"},
                    {"name": "clicks", "type": "INTEGER", "default": "0"},
                ],
            },
        ],
    },
    # ═══════════════════════════════════════════════════════════════════════════
    # IT & INFRASTRUCTURE (15 tables)
    # ═══════════════════════════════════════════════════════════════════════════
    "it_infra": {
        "description": "IT Infrastructure and Asset Management",
        "tables": [
            {
                "name": "it_assets",
                "columns": [
                    {"name": "asset_id", "type": "SERIAL", "primary_key": True},
                    {"name": "asset_tag", "type": "VARCHAR(50)", "unique": True},
                    {"name": "asset_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "asset_type", "type": "VARCHAR(50)"},
                    {"name": "manufacturer", "type": "VARCHAR(200)"},
                    {"name": "model", "type": "VARCHAR(200)"},
                    {"name": "serial_number", "type": "VARCHAR(100)"},
                    {"name": "purchase_date", "type": "DATE"},
                    {"name": "purchase_price", "type": "DECIMAL(15,2)"},
                    {"name": "warranty_expiry", "type": "DATE"},
                    {"name": "assigned_to", "type": "INTEGER"},
                    {"name": "location", "type": "VARCHAR(200)"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'active'"},
                ],
            },
            {
                "name": "servers",
                "columns": [
                    {"name": "server_id", "type": "SERIAL", "primary_key": True},
                    {"name": "asset_id", "type": "INTEGER", "fk": "it_assets.asset_id"},
                    {"name": "hostname", "type": "VARCHAR(200)", "not_null": True, "unique": True},
                    {"name": "ip_address", "type": "VARCHAR(50)"},
                    {"name": "os", "type": "VARCHAR(100)"},
                    {"name": "os_version", "type": "VARCHAR(50)"},
                    {"name": "cpu_cores", "type": "INTEGER"},
                    {"name": "ram_gb", "type": "INTEGER"},
                    {"name": "storage_gb", "type": "INTEGER"},
                    {"name": "environment", "type": "VARCHAR(50)"},
                    {"name": "role", "type": "VARCHAR(100)"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'running'"},
                ],
            },
            {
                "name": "applications",
                "columns": [
                    {"name": "app_id", "type": "SERIAL", "primary_key": True},
                    {"name": "app_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "version", "type": "VARCHAR(50)"},
                    {"name": "vendor", "type": "VARCHAR(200)"},
                    {"name": "license_type", "type": "VARCHAR(50)"},
                    {"name": "license_count", "type": "INTEGER"},
                    {"name": "license_expiry", "type": "DATE"},
                    {"name": "owner_id", "type": "INTEGER"},
                    {"name": "criticality", "type": "VARCHAR(20)"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'active'"},
                ],
            },
            {
                "name": "app_server_map",
                "columns": [
                    {"name": "map_id", "type": "SERIAL", "primary_key": True},
                    {"name": "app_id", "type": "INTEGER", "not_null": True, "fk": "applications.app_id"},
                    {"name": "server_id", "type": "INTEGER", "not_null": True, "fk": "servers.server_id"},
                    {"name": "environment", "type": "VARCHAR(50)"},
                ],
            },
            {
                "name": "network_devices",
                "columns": [
                    {"name": "device_id", "type": "SERIAL", "primary_key": True},
                    {"name": "asset_id", "type": "INTEGER", "fk": "it_assets.asset_id"},
                    {"name": "device_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "device_type", "type": "VARCHAR(50)"},
                    {"name": "ip_address", "type": "VARCHAR(50)"},
                    {"name": "mac_address", "type": "VARCHAR(20)"},
                    {"name": "location", "type": "VARCHAR(200)"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'active'"},
                ],
            },
            {
                "name": "it_incidents",
                "columns": [
                    {"name": "incident_id", "type": "SERIAL", "primary_key": True},
                    {"name": "incident_number", "type": "VARCHAR(50)", "unique": True},
                    {"name": "title", "type": "VARCHAR(500)", "not_null": True},
                    {"name": "description", "type": "TEXT"},
                    {"name": "category", "type": "VARCHAR(100)"},
                    {"name": "priority", "type": "VARCHAR(20)"},
                    {"name": "severity", "type": "VARCHAR(20)"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'new'"},
                    {"name": "reported_by", "type": "INTEGER"},
                    {"name": "assigned_to", "type": "INTEGER"},
                    {"name": "affected_asset_id", "type": "INTEGER", "fk": "it_assets.asset_id"},
                    {"name": "resolution", "type": "TEXT"},
                    {"name": "resolved_at", "type": "TIMESTAMP"},
                ],
            },
            {
                "name": "change_tickets",
                "columns": [
                    {"name": "change_id", "type": "SERIAL", "primary_key": True},
                    {"name": "change_number", "type": "VARCHAR(50)", "unique": True},
                    {"name": "title", "type": "VARCHAR(500)", "not_null": True},
                    {"name": "description", "type": "TEXT"},
                    {"name": "change_type", "type": "VARCHAR(50)"},
                    {"name": "risk_level", "type": "VARCHAR(20)"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'draft'"},
                    {"name": "requested_by", "type": "INTEGER"},
                    {"name": "assigned_to", "type": "INTEGER"},
                    {"name": "planned_start", "type": "TIMESTAMP"},
                    {"name": "planned_end", "type": "TIMESTAMP"},
                    {"name": "actual_start", "type": "TIMESTAMP"},
                    {"name": "actual_end", "type": "TIMESTAMP"},
                    {"name": "approved_by", "type": "INTEGER"},
                ],
            },
            {
                "name": "service_requests",
                "columns": [
                    {"name": "request_id", "type": "SERIAL", "primary_key": True},
                    {"name": "request_number", "type": "VARCHAR(50)", "unique": True},
                    {"name": "title", "type": "VARCHAR(500)", "not_null": True},
                    {"name": "description", "type": "TEXT"},
                    {"name": "category", "type": "VARCHAR(100)"},
                    {"name": "priority", "type": "VARCHAR(20)"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'new'"},
                    {"name": "requested_by", "type": "INTEGER"},
                    {"name": "assigned_to", "type": "INTEGER"},
                    {"name": "fulfilled_at", "type": "TIMESTAMP"},
                ],
            },
            {
                "name": "software_licenses",
                "columns": [
                    {"name": "license_id", "type": "SERIAL", "primary_key": True},
                    {"name": "app_id", "type": "INTEGER", "fk": "applications.app_id"},
                    {"name": "license_key", "type": "VARCHAR(500)"},
                    {"name": "license_type", "type": "VARCHAR(50)"},
                    {"name": "seats", "type": "INTEGER"},
                    {"name": "seats_used", "type": "INTEGER", "default": "0"},
                    {"name": "purchase_date", "type": "DATE"},
                    {"name": "expiry_date", "type": "DATE"},
                    {"name": "cost", "type": "DECIMAL(15,2)"},
                    {"name": "vendor", "type": "VARCHAR(200)"},
                ],
            },
            {
                "name": "backup_jobs",
                "columns": [
                    {"name": "job_id", "type": "SERIAL", "primary_key": True},
                    {"name": "job_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "server_id", "type": "INTEGER", "fk": "servers.server_id"},
                    {"name": "backup_type", "type": "VARCHAR(50)"},
                    {"name": "schedule", "type": "VARCHAR(100)"},
                    {"name": "retention_days", "type": "INTEGER"},
                    {"name": "destination", "type": "VARCHAR(500)"},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                    {"name": "last_run", "type": "TIMESTAMP"},
                    {"name": "last_status", "type": "VARCHAR(50)"},
                ],
            },
            {
                "name": "backup_history",
                "columns": [
                    {"name": "history_id", "type": "SERIAL", "primary_key": True},
                    {"name": "job_id", "type": "INTEGER", "not_null": True, "fk": "backup_jobs.job_id"},
                    {"name": "start_time", "type": "TIMESTAMP"},
                    {"name": "end_time", "type": "TIMESTAMP"},
                    {"name": "status", "type": "VARCHAR(50)"},
                    {"name": "size_mb", "type": "DECIMAL(15,2)"},
                    {"name": "error_message", "type": "TEXT"},
                ],
            },
            {
                "name": "monitoring_alerts",
                "columns": [
                    {"name": "alert_id", "type": "SERIAL", "primary_key": True},
                    {"name": "alert_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "server_id", "type": "INTEGER", "fk": "servers.server_id"},
                    {"name": "app_id", "type": "INTEGER", "fk": "applications.app_id"},
                    {"name": "severity", "type": "VARCHAR(20)"},
                    {"name": "message", "type": "TEXT"},
                    {"name": "triggered_at", "type": "TIMESTAMP"},
                    {"name": "acknowledged_at", "type": "TIMESTAMP"},
                    {"name": "resolved_at", "type": "TIMESTAMP"},
                    {"name": "acknowledged_by", "type": "INTEGER"},
                ],
            },
            {
                "name": "maintenance_windows",
                "columns": [
                    {"name": "window_id", "type": "SERIAL", "primary_key": True},
                    {"name": "title", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "description", "type": "TEXT"},
                    {"name": "start_time", "type": "TIMESTAMP", "not_null": True},
                    {"name": "end_time", "type": "TIMESTAMP", "not_null": True},
                    {"name": "affected_systems", "type": "TEXT"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'scheduled'"},
                ],
            },
            {
                "name": "deployment_history",
                "columns": [
                    {"name": "deployment_id", "type": "SERIAL", "primary_key": True},
                    {"name": "app_id", "type": "INTEGER", "fk": "applications.app_id"},
                    {"name": "server_id", "type": "INTEGER", "fk": "servers.server_id"},
                    {"name": "version", "type": "VARCHAR(50)"},
                    {"name": "deployed_at", "type": "TIMESTAMP"},
                    {"name": "deployed_by", "type": "INTEGER"},
                    {"name": "status", "type": "VARCHAR(50)"},
                    {"name": "rollback_version", "type": "VARCHAR(50)"},
                    {"name": "notes", "type": "TEXT"},
                ],
            },
            {
                "name": "ssl_certificates",
                "columns": [
                    {"name": "cert_id", "type": "SERIAL", "primary_key": True},
                    {"name": "domain", "type": "VARCHAR(255)", "not_null": True},
                    {"name": "issuer", "type": "VARCHAR(200)"},
                    {"name": "issued_date", "type": "DATE"},
                    {"name": "expiry_date", "type": "DATE"},
                    {"name": "cert_type", "type": "VARCHAR(50)"},
                    {"name": "server_id", "type": "INTEGER", "fk": "servers.server_id"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'active'"},
                ],
            },
        ],
    },
}

