"""
Extended domain definitions for synthetic 250-table database generator.
Part 2: E-Commerce, CRM, Inventory, Healthcare, Education, Marketing
"""

from typing import Dict, List, Any

DOMAINS_EXTENDED: Dict[str, Dict[str, Any]] = {
    # ═══════════════════════════════════════════════════════════════════════════
    # E-COMMERCE (35 tables)
    # ═══════════════════════════════════════════════════════════════════════════
    "ecommerce": {
        "description": "E-Commerce and Online Retail",
        "tables": [
            {
                "name": "customers",
                "columns": [
                    {"name": "customer_id", "type": "SERIAL", "primary_key": True},
                    {"name": "email", "type": "VARCHAR(255)", "not_null": True, "unique": True},
                    {"name": "password_hash", "type": "VARCHAR(255)"},
                    {"name": "first_name", "type": "VARCHAR(100)"},
                    {"name": "last_name", "type": "VARCHAR(100)"},
                    {"name": "phone", "type": "VARCHAR(20)"},
                    {"name": "date_of_birth", "type": "DATE"},
                    {"name": "gender", "type": "VARCHAR(10)"},
                    {"name": "registration_date", "type": "TIMESTAMP", "default": "CURRENT_TIMESTAMP"},
                    {"name": "last_login", "type": "TIMESTAMP"},
                    {"name": "is_verified", "type": "BOOLEAN", "default": "false"},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                    {"name": "customer_tier", "type": "VARCHAR(20)", "default": "'standard'"},
                    {"name": "total_orders", "type": "INTEGER", "default": "0"},
                    {"name": "total_spent", "type": "DECIMAL(15,2)", "default": "0"},
                ],
            },
            {
                "name": "customer_addresses",
                "columns": [
                    {"name": "address_id", "type": "SERIAL", "primary_key": True},
                    {"name": "customer_id", "type": "INTEGER", "not_null": True, "fk": "customers.customer_id"},
                    {"name": "address_type", "type": "VARCHAR(20)", "default": "'shipping'"},
                    {"name": "address_line1", "type": "VARCHAR(255)", "not_null": True},
                    {"name": "address_line2", "type": "VARCHAR(255)"},
                    {"name": "city", "type": "VARCHAR(100)", "not_null": True},
                    {"name": "state_province", "type": "VARCHAR(100)"},
                    {"name": "postal_code", "type": "VARCHAR(20)"},
                    {"name": "country_code", "type": "VARCHAR(3)", "not_null": True},
                    {"name": "is_default", "type": "BOOLEAN", "default": "false"},
                ],
            },
            {
                "name": "product_categories",
                "columns": [
                    {"name": "category_id", "type": "SERIAL", "primary_key": True},
                    {"name": "category_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "slug", "type": "VARCHAR(200)", "unique": True},
                    {"name": "parent_category_id", "type": "INTEGER", "fk": "product_categories.category_id"},
                    {"name": "description", "type": "TEXT"},
                    {"name": "image_url", "type": "VARCHAR(500)"},
                    {"name": "sort_order", "type": "INTEGER", "default": "0"},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                    {"name": "meta_title", "type": "VARCHAR(200)"},
                    {"name": "meta_description", "type": "TEXT"},
                ],
            },
            {
                "name": "brands",
                "columns": [
                    {"name": "brand_id", "type": "SERIAL", "primary_key": True},
                    {"name": "brand_name", "type": "VARCHAR(200)", "not_null": True, "unique": True},
                    {"name": "slug", "type": "VARCHAR(200)", "unique": True},
                    {"name": "logo_url", "type": "VARCHAR(500)"},
                    {"name": "description", "type": "TEXT"},
                    {"name": "website", "type": "VARCHAR(255)"},
                    {"name": "is_featured", "type": "BOOLEAN", "default": "false"},
                ],
            },
            {
                "name": "products",
                "columns": [
                    {"name": "product_id", "type": "SERIAL", "primary_key": True},
                    {"name": "sku", "type": "VARCHAR(100)", "not_null": True, "unique": True},
                    {"name": "product_name", "type": "VARCHAR(300)", "not_null": True},
                    {"name": "slug", "type": "VARCHAR(300)", "unique": True},
                    {"name": "brand_id", "type": "INTEGER", "fk": "brands.brand_id"},
                    {"name": "category_id", "type": "INTEGER", "fk": "product_categories.category_id"},
                    {"name": "short_description", "type": "VARCHAR(500)"},
                    {"name": "long_description", "type": "TEXT"},
                    {"name": "base_price", "type": "DECIMAL(15,2)", "not_null": True},
                    {"name": "sale_price", "type": "DECIMAL(15,2)"},
                    {"name": "cost_price", "type": "DECIMAL(15,2)"},
                    {"name": "weight_kg", "type": "DECIMAL(10,3)"},
                    {"name": "dimensions_cm", "type": "VARCHAR(50)"},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                    {"name": "is_featured", "type": "BOOLEAN", "default": "false"},
                    {"name": "is_digital", "type": "BOOLEAN", "default": "false"},
                    {"name": "tax_class", "type": "VARCHAR(50)"},
                    {"name": "meta_title", "type": "VARCHAR(200)"},
                    {"name": "meta_description", "type": "TEXT"},
                ],
            },
            {
                "name": "product_variants",
                "columns": [
                    {"name": "variant_id", "type": "SERIAL", "primary_key": True},
                    {"name": "product_id", "type": "INTEGER", "not_null": True, "fk": "products.product_id"},
                    {"name": "variant_sku", "type": "VARCHAR(100)", "unique": True},
                    {"name": "variant_name", "type": "VARCHAR(200)"},
                    {"name": "price_modifier", "type": "DECIMAL(10,2)", "default": "0"},
                    {"name": "weight_modifier", "type": "DECIMAL(10,3)", "default": "0"},
                    {"name": "stock_quantity", "type": "INTEGER", "default": "0"},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                ],
            },
            {
                "name": "product_attributes",
                "columns": [
                    {"name": "attribute_id", "type": "SERIAL", "primary_key": True},
                    {"name": "attribute_name", "type": "VARCHAR(100)", "not_null": True},
                    {"name": "attribute_type", "type": "VARCHAR(50)"},
                    {"name": "is_filterable", "type": "BOOLEAN", "default": "false"},
                    {"name": "is_required", "type": "BOOLEAN", "default": "false"},
                ],
            },
            {
                "name": "product_attribute_values",
                "columns": [
                    {"name": "value_id", "type": "SERIAL", "primary_key": True},
                    {"name": "product_id", "type": "INTEGER", "not_null": True, "fk": "products.product_id"},
                    {"name": "attribute_id", "type": "INTEGER", "not_null": True, "fk": "product_attributes.attribute_id"},
                    {"name": "attribute_value", "type": "VARCHAR(500)"},
                ],
            },
            {
                "name": "product_images",
                "columns": [
                    {"name": "image_id", "type": "SERIAL", "primary_key": True},
                    {"name": "product_id", "type": "INTEGER", "not_null": True, "fk": "products.product_id"},
                    {"name": "variant_id", "type": "INTEGER", "fk": "product_variants.variant_id"},
                    {"name": "image_url", "type": "VARCHAR(500)", "not_null": True},
                    {"name": "alt_text", "type": "VARCHAR(200)"},
                    {"name": "sort_order", "type": "INTEGER", "default": "0"},
                    {"name": "is_primary", "type": "BOOLEAN", "default": "false"},
                ],
            },
            {
                "name": "product_reviews",
                "columns": [
                    {"name": "review_id", "type": "SERIAL", "primary_key": True},
                    {"name": "product_id", "type": "INTEGER", "not_null": True, "fk": "products.product_id"},
                    {"name": "customer_id", "type": "INTEGER", "fk": "customers.customer_id"},
                    {"name": "rating", "type": "INTEGER", "not_null": True},
                    {"name": "title", "type": "VARCHAR(200)"},
                    {"name": "review_text", "type": "TEXT"},
                    {"name": "is_verified_purchase", "type": "BOOLEAN", "default": "false"},
                    {"name": "is_approved", "type": "BOOLEAN", "default": "false"},
                    {"name": "helpful_votes", "type": "INTEGER", "default": "0"},
                ],
            },
            {
                "name": "shopping_carts",
                "columns": [
                    {"name": "cart_id", "type": "SERIAL", "primary_key": True},
                    {"name": "customer_id", "type": "INTEGER", "fk": "customers.customer_id"},
                    {"name": "session_id", "type": "VARCHAR(100)"},
                    {"name": "currency", "type": "VARCHAR(3)", "default": "'USD'"},
                    {"name": "subtotal", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "discount_total", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "tax_total", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "last_activity", "type": "TIMESTAMP"},
                ],
            },
            {
                "name": "cart_items",
                "columns": [
                    {"name": "cart_item_id", "type": "SERIAL", "primary_key": True},
                    {"name": "cart_id", "type": "INTEGER", "not_null": True, "fk": "shopping_carts.cart_id"},
                    {"name": "product_id", "type": "INTEGER", "not_null": True, "fk": "products.product_id"},
                    {"name": "variant_id", "type": "INTEGER", "fk": "product_variants.variant_id"},
                    {"name": "quantity", "type": "INTEGER", "not_null": True, "default": "1"},
                    {"name": "unit_price", "type": "DECIMAL(15,2)", "not_null": True},
                    {"name": "added_at", "type": "TIMESTAMP", "default": "CURRENT_TIMESTAMP"},
                ],
            },
            {
                "name": "wishlists",
                "columns": [
                    {"name": "wishlist_id", "type": "SERIAL", "primary_key": True},
                    {"name": "customer_id", "type": "INTEGER", "not_null": True, "fk": "customers.customer_id"},
                    {"name": "wishlist_name", "type": "VARCHAR(100)", "default": "'My Wishlist'"},
                    {"name": "is_public", "type": "BOOLEAN", "default": "false"},
                ],
            },
            {
                "name": "wishlist_items",
                "columns": [
                    {"name": "wishlist_item_id", "type": "SERIAL", "primary_key": True},
                    {"name": "wishlist_id", "type": "INTEGER", "not_null": True, "fk": "wishlists.wishlist_id"},
                    {"name": "product_id", "type": "INTEGER", "not_null": True, "fk": "products.product_id"},
                    {"name": "variant_id", "type": "INTEGER", "fk": "product_variants.variant_id"},
                    {"name": "added_at", "type": "TIMESTAMP", "default": "CURRENT_TIMESTAMP"},
                    {"name": "notes", "type": "VARCHAR(500)"},
                ],
            },
            {
                "name": "orders",
                "columns": [
                    {"name": "order_id", "type": "SERIAL", "primary_key": True},
                    {"name": "order_number", "type": "VARCHAR(50)", "not_null": True, "unique": True},
                    {"name": "customer_id", "type": "INTEGER", "fk": "customers.customer_id"},
                    {"name": "order_date", "type": "TIMESTAMP", "not_null": True, "default": "CURRENT_TIMESTAMP"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'pending'"},
                    {"name": "subtotal", "type": "DECIMAL(15,2)", "not_null": True},
                    {"name": "discount_total", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "shipping_total", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "tax_total", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "grand_total", "type": "DECIMAL(15,2)", "not_null": True},
                    {"name": "currency", "type": "VARCHAR(3)", "default": "'USD'"},
                    {"name": "shipping_address_id", "type": "INTEGER", "fk": "customer_addresses.address_id"},
                    {"name": "billing_address_id", "type": "INTEGER", "fk": "customer_addresses.address_id"},
                    {"name": "shipping_method_id", "type": "INTEGER", "fk": "shipping_methods.shipping_method_id"},
                    {"name": "payment_method", "type": "VARCHAR(50)"},
                    {"name": "notes", "type": "TEXT"},
                    {"name": "ip_address", "type": "VARCHAR(50)"},
                ],
            },
            {
                "name": "order_items",
                "columns": [
                    {"name": "order_item_id", "type": "SERIAL", "primary_key": True},
                    {"name": "order_id", "type": "INTEGER", "not_null": True, "fk": "orders.order_id"},
                    {"name": "product_id", "type": "INTEGER", "not_null": True, "fk": "products.product_id"},
                    {"name": "variant_id", "type": "INTEGER", "fk": "product_variants.variant_id"},
                    {"name": "product_name", "type": "VARCHAR(300)"},
                    {"name": "sku", "type": "VARCHAR(100)"},
                    {"name": "quantity", "type": "INTEGER", "not_null": True},
                    {"name": "unit_price", "type": "DECIMAL(15,2)", "not_null": True},
                    {"name": "discount_amount", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "tax_amount", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "line_total", "type": "DECIMAL(15,2)", "not_null": True},
                ],
            },
            {
                "name": "order_status_history",
                "columns": [
                    {"name": "history_id", "type": "SERIAL", "primary_key": True},
                    {"name": "order_id", "type": "INTEGER", "not_null": True, "fk": "orders.order_id"},
                    {"name": "status", "type": "VARCHAR(50)", "not_null": True},
                    {"name": "changed_at", "type": "TIMESTAMP", "default": "CURRENT_TIMESTAMP"},
                    {"name": "changed_by", "type": "INTEGER"},
                    {"name": "notes", "type": "TEXT"},
                ],
            },
            {
                "name": "shipping_methods",
                "columns": [
                    {"name": "shipping_method_id", "type": "SERIAL", "primary_key": True},
                    {"name": "method_name", "type": "VARCHAR(100)", "not_null": True},
                    {"name": "carrier", "type": "VARCHAR(100)"},
                    {"name": "base_rate", "type": "DECIMAL(10,2)", "not_null": True},
                    {"name": "per_kg_rate", "type": "DECIMAL(10,2)", "default": "0"},
                    {"name": "estimated_days_min", "type": "INTEGER"},
                    {"name": "estimated_days_max", "type": "INTEGER"},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                ],
            },
            {
                "name": "shipments",
                "columns": [
                    {"name": "shipment_id", "type": "SERIAL", "primary_key": True},
                    {"name": "order_id", "type": "INTEGER", "not_null": True, "fk": "orders.order_id"},
                    {"name": "tracking_number", "type": "VARCHAR(100)"},
                    {"name": "carrier", "type": "VARCHAR(100)"},
                    {"name": "shipped_date", "type": "TIMESTAMP"},
                    {"name": "delivered_date", "type": "TIMESTAMP"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'pending'"},
                    {"name": "shipping_cost", "type": "DECIMAL(10,2)"},
                ],
            },
            {
                "name": "shipment_items",
                "columns": [
                    {"name": "shipment_item_id", "type": "SERIAL", "primary_key": True},
                    {"name": "shipment_id", "type": "INTEGER", "not_null": True, "fk": "shipments.shipment_id"},
                    {"name": "order_item_id", "type": "INTEGER", "not_null": True, "fk": "order_items.order_item_id"},
                    {"name": "quantity_shipped", "type": "INTEGER", "not_null": True},
                ],
            },
            {
                "name": "order_returns",
                "columns": [
                    {"name": "return_id", "type": "SERIAL", "primary_key": True},
                    {"name": "order_id", "type": "INTEGER", "not_null": True, "fk": "orders.order_id"},
                    {"name": "return_number", "type": "VARCHAR(50)", "unique": True},
                    {"name": "requested_date", "type": "TIMESTAMP", "default": "CURRENT_TIMESTAMP"},
                    {"name": "reason", "type": "VARCHAR(200)"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'requested'"},
                    {"name": "refund_amount", "type": "DECIMAL(15,2)"},
                    {"name": "refund_method", "type": "VARCHAR(50)"},
                    {"name": "processed_date", "type": "TIMESTAMP"},
                    {"name": "notes", "type": "TEXT"},
                ],
            },
            {
                "name": "return_items",
                "columns": [
                    {"name": "return_item_id", "type": "SERIAL", "primary_key": True},
                    {"name": "return_id", "type": "INTEGER", "not_null": True, "fk": "order_returns.return_id"},
                    {"name": "order_item_id", "type": "INTEGER", "not_null": True, "fk": "order_items.order_item_id"},
                    {"name": "quantity_returned", "type": "INTEGER", "not_null": True},
                    {"name": "condition", "type": "VARCHAR(50)"},
                    {"name": "refund_amount", "type": "DECIMAL(15,2)"},
                ],
            },
            {
                "name": "coupons",
                "columns": [
                    {"name": "coupon_id", "type": "SERIAL", "primary_key": True},
                    {"name": "coupon_code", "type": "VARCHAR(50)", "not_null": True, "unique": True},
                    {"name": "description", "type": "VARCHAR(500)"},
                    {"name": "discount_type", "type": "VARCHAR(20)", "not_null": True},
                    {"name": "discount_value", "type": "DECIMAL(15,2)", "not_null": True},
                    {"name": "minimum_purchase", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "maximum_discount", "type": "DECIMAL(15,2)"},
                    {"name": "usage_limit", "type": "INTEGER"},
                    {"name": "usage_count", "type": "INTEGER", "default": "0"},
                    {"name": "per_customer_limit", "type": "INTEGER"},
                    {"name": "start_date", "type": "TIMESTAMP"},
                    {"name": "end_date", "type": "TIMESTAMP"},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                ],
            },
            {
                "name": "coupon_usage",
                "columns": [
                    {"name": "usage_id", "type": "SERIAL", "primary_key": True},
                    {"name": "coupon_id", "type": "INTEGER", "not_null": True, "fk": "coupons.coupon_id"},
                    {"name": "order_id", "type": "INTEGER", "not_null": True, "fk": "orders.order_id"},
                    {"name": "customer_id", "type": "INTEGER", "fk": "customers.customer_id"},
                    {"name": "discount_applied", "type": "DECIMAL(15,2)", "not_null": True},
                    {"name": "used_at", "type": "TIMESTAMP", "default": "CURRENT_TIMESTAMP"},
                ],
            },
            {
                "name": "gift_cards",
                "columns": [
                    {"name": "gift_card_id", "type": "SERIAL", "primary_key": True},
                    {"name": "card_code", "type": "VARCHAR(50)", "not_null": True, "unique": True},
                    {"name": "initial_balance", "type": "DECIMAL(15,2)", "not_null": True},
                    {"name": "current_balance", "type": "DECIMAL(15,2)", "not_null": True},
                    {"name": "currency", "type": "VARCHAR(3)", "default": "'USD'"},
                    {"name": "purchaser_customer_id", "type": "INTEGER", "fk": "customers.customer_id"},
                    {"name": "recipient_email", "type": "VARCHAR(255)"},
                    {"name": "message", "type": "TEXT"},
                    {"name": "purchase_date", "type": "TIMESTAMP"},
                    {"name": "expiry_date", "type": "TIMESTAMP"},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                ],
            },
            {
                "name": "payment_transactions",
                "columns": [
                    {"name": "transaction_id", "type": "SERIAL", "primary_key": True},
                    {"name": "order_id", "type": "INTEGER", "not_null": True, "fk": "orders.order_id"},
                    {"name": "transaction_type", "type": "VARCHAR(50)", "not_null": True},
                    {"name": "amount", "type": "DECIMAL(15,2)", "not_null": True},
                    {"name": "currency", "type": "VARCHAR(3)", "default": "'USD'"},
                    {"name": "payment_method", "type": "VARCHAR(50)"},
                    {"name": "gateway", "type": "VARCHAR(100)"},
                    {"name": "gateway_transaction_id", "type": "VARCHAR(200)"},
                    {"name": "status", "type": "VARCHAR(50)"},
                    {"name": "error_message", "type": "TEXT"},
                    {"name": "processed_at", "type": "TIMESTAMP", "default": "CURRENT_TIMESTAMP"},
                ],
            },
            {
                "name": "product_tags",
                "columns": [
                    {"name": "tag_id", "type": "SERIAL", "primary_key": True},
                    {"name": "tag_name", "type": "VARCHAR(100)", "not_null": True, "unique": True},
                    {"name": "slug", "type": "VARCHAR(100)", "unique": True},
                ],
            },
            {
                "name": "product_tag_map",
                "columns": [
                    {"name": "product_tag_id", "type": "SERIAL", "primary_key": True},
                    {"name": "product_id", "type": "INTEGER", "not_null": True, "fk": "products.product_id"},
                    {"name": "tag_id", "type": "INTEGER", "not_null": True, "fk": "product_tags.tag_id"},
                ],
            },
            {
                "name": "related_products",
                "columns": [
                    {"name": "relation_id", "type": "SERIAL", "primary_key": True},
                    {"name": "product_id", "type": "INTEGER", "not_null": True, "fk": "products.product_id"},
                    {"name": "related_product_id", "type": "INTEGER", "not_null": True, "fk": "products.product_id"},
                    {"name": "relation_type", "type": "VARCHAR(50)"},
                    {"name": "sort_order", "type": "INTEGER", "default": "0"},
                ],
            },
            {
                "name": "product_bundles",
                "columns": [
                    {"name": "bundle_id", "type": "SERIAL", "primary_key": True},
                    {"name": "bundle_product_id", "type": "INTEGER", "not_null": True, "fk": "products.product_id"},
                    {"name": "discount_percentage", "type": "DECIMAL(5,2)", "default": "0"},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                ],
            },
            {
                "name": "bundle_items",
                "columns": [
                    {"name": "bundle_item_id", "type": "SERIAL", "primary_key": True},
                    {"name": "bundle_id", "type": "INTEGER", "not_null": True, "fk": "product_bundles.bundle_id"},
                    {"name": "product_id", "type": "INTEGER", "not_null": True, "fk": "products.product_id"},
                    {"name": "quantity", "type": "INTEGER", "not_null": True, "default": "1"},
                    {"name": "is_required", "type": "BOOLEAN", "default": "true"},
                ],
            },
            {
                "name": "promotions",
                "columns": [
                    {"name": "promotion_id", "type": "SERIAL", "primary_key": True},
                    {"name": "promotion_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "promotion_type", "type": "VARCHAR(50)"},
                    {"name": "discount_type", "type": "VARCHAR(20)"},
                    {"name": "discount_value", "type": "DECIMAL(15,2)"},
                    {"name": "conditions", "type": "JSONB"},
                    {"name": "start_date", "type": "TIMESTAMP"},
                    {"name": "end_date", "type": "TIMESTAMP"},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                    {"name": "priority", "type": "INTEGER", "default": "0"},
                ],
            },
            {
                "name": "promotion_products",
                "columns": [
                    {"name": "promo_product_id", "type": "SERIAL", "primary_key": True},
                    {"name": "promotion_id", "type": "INTEGER", "not_null": True, "fk": "promotions.promotion_id"},
                    {"name": "product_id", "type": "INTEGER", "fk": "products.product_id"},
                    {"name": "category_id", "type": "INTEGER", "fk": "product_categories.category_id"},
                ],
            },
        ],
    },
    # ═══════════════════════════════════════════════════════════════════════════
    # INVENTORY & WAREHOUSE (25 tables)
    # ═══════════════════════════════════════════════════════════════════════════
    "inventory": {
        "description": "Inventory and Warehouse Management",
        "tables": [
            {
                "name": "warehouses",
                "columns": [
                    {"name": "warehouse_id", "type": "SERIAL", "primary_key": True},
                    {"name": "warehouse_code", "type": "VARCHAR(20)", "not_null": True, "unique": True},
                    {"name": "warehouse_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "address_line1", "type": "VARCHAR(255)"},
                    {"name": "city", "type": "VARCHAR(100)"},
                    {"name": "state", "type": "VARCHAR(100)"},
                    {"name": "country", "type": "VARCHAR(100)"},
                    {"name": "postal_code", "type": "VARCHAR(20)"},
                    {"name": "capacity_sqft", "type": "INTEGER"},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                    {"name": "manager_id", "type": "INTEGER"},
                ],
            },
            {
                "name": "warehouse_zones",
                "columns": [
                    {"name": "zone_id", "type": "SERIAL", "primary_key": True},
                    {"name": "warehouse_id", "type": "INTEGER", "not_null": True, "fk": "warehouses.warehouse_id"},
                    {"name": "zone_code", "type": "VARCHAR(20)", "not_null": True},
                    {"name": "zone_name", "type": "VARCHAR(100)"},
                    {"name": "zone_type", "type": "VARCHAR(50)"},
                    {"name": "temperature_controlled", "type": "BOOLEAN", "default": "false"},
                    {"name": "min_temp", "type": "DECIMAL(5,2)"},
                    {"name": "max_temp", "type": "DECIMAL(5,2)"},
                ],
            },
            {
                "name": "storage_locations",
                "columns": [
                    {"name": "location_id", "type": "SERIAL", "primary_key": True},
                    {"name": "zone_id", "type": "INTEGER", "not_null": True, "fk": "warehouse_zones.zone_id"},
                    {"name": "location_code", "type": "VARCHAR(50)", "not_null": True},
                    {"name": "aisle", "type": "VARCHAR(10)"},
                    {"name": "rack", "type": "VARCHAR(10)"},
                    {"name": "shelf", "type": "VARCHAR(10)"},
                    {"name": "bin", "type": "VARCHAR(10)"},
                    {"name": "max_weight_kg", "type": "DECIMAL(10,2)"},
                    {"name": "max_volume_cbm", "type": "DECIMAL(10,3)"},
                    {"name": "is_available", "type": "BOOLEAN", "default": "true"},
                ],
            },
            {
                "name": "inventory_items",
                "columns": [
                    {"name": "inventory_id", "type": "SERIAL", "primary_key": True},
                    {"name": "product_id", "type": "INTEGER", "not_null": True},
                    {"name": "variant_id", "type": "INTEGER"},
                    {"name": "warehouse_id", "type": "INTEGER", "not_null": True, "fk": "warehouses.warehouse_id"},
                    {"name": "location_id", "type": "INTEGER", "fk": "storage_locations.location_id"},
                    {"name": "quantity_on_hand", "type": "INTEGER", "not_null": True, "default": "0"},
                    {"name": "quantity_reserved", "type": "INTEGER", "default": "0"},
                    {"name": "quantity_available", "type": "INTEGER", "default": "0"},
                    {"name": "reorder_point", "type": "INTEGER"},
                    {"name": "reorder_quantity", "type": "INTEGER"},
                    {"name": "last_count_date", "type": "DATE"},
                ],
            },
            {
                "name": "inventory_lots",
                "columns": [
                    {"name": "lot_id", "type": "SERIAL", "primary_key": True},
                    {"name": "inventory_id", "type": "INTEGER", "not_null": True, "fk": "inventory_items.inventory_id"},
                    {"name": "lot_number", "type": "VARCHAR(100)", "not_null": True},
                    {"name": "quantity", "type": "INTEGER", "not_null": True},
                    {"name": "manufacture_date", "type": "DATE"},
                    {"name": "expiry_date", "type": "DATE"},
                    {"name": "received_date", "type": "DATE"},
                    {"name": "cost_per_unit", "type": "DECIMAL(15,4)"},
                ],
            },
            {
                "name": "inventory_transactions",
                "columns": [
                    {"name": "transaction_id", "type": "SERIAL", "primary_key": True},
                    {"name": "inventory_id", "type": "INTEGER", "not_null": True, "fk": "inventory_items.inventory_id"},
                    {"name": "transaction_type", "type": "VARCHAR(50)", "not_null": True},
                    {"name": "quantity", "type": "INTEGER", "not_null": True},
                    {"name": "reference_type", "type": "VARCHAR(50)"},
                    {"name": "reference_id", "type": "INTEGER"},
                    {"name": "notes", "type": "TEXT"},
                    {"name": "transaction_date", "type": "TIMESTAMP", "default": "CURRENT_TIMESTAMP"},
                    {"name": "performed_by", "type": "INTEGER"},
                ],
            },
            {
                "name": "suppliers",
                "columns": [
                    {"name": "supplier_id", "type": "SERIAL", "primary_key": True},
                    {"name": "supplier_code", "type": "VARCHAR(50)", "unique": True},
                    {"name": "supplier_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "contact_name", "type": "VARCHAR(200)"},
                    {"name": "email", "type": "VARCHAR(255)"},
                    {"name": "phone", "type": "VARCHAR(20)"},
                    {"name": "address", "type": "TEXT"},
                    {"name": "country", "type": "VARCHAR(100)"},
                    {"name": "payment_terms", "type": "VARCHAR(50)"},
                    {"name": "lead_time_days", "type": "INTEGER"},
                    {"name": "rating", "type": "DECIMAL(3,2)"},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                ],
            },
            {
                "name": "supplier_products",
                "columns": [
                    {"name": "supplier_product_id", "type": "SERIAL", "primary_key": True},
                    {"name": "supplier_id", "type": "INTEGER", "not_null": True, "fk": "suppliers.supplier_id"},
                    {"name": "product_id", "type": "INTEGER", "not_null": True},
                    {"name": "supplier_sku", "type": "VARCHAR(100)"},
                    {"name": "unit_cost", "type": "DECIMAL(15,4)"},
                    {"name": "minimum_order_qty", "type": "INTEGER", "default": "1"},
                    {"name": "lead_time_days", "type": "INTEGER"},
                    {"name": "is_preferred", "type": "BOOLEAN", "default": "false"},
                ],
            },
            {
                "name": "purchase_orders",
                "columns": [
                    {"name": "po_id", "type": "SERIAL", "primary_key": True},
                    {"name": "po_number", "type": "VARCHAR(50)", "not_null": True, "unique": True},
                    {"name": "supplier_id", "type": "INTEGER", "not_null": True, "fk": "suppliers.supplier_id"},
                    {"name": "warehouse_id", "type": "INTEGER", "fk": "warehouses.warehouse_id"},
                    {"name": "order_date", "type": "DATE", "not_null": True},
                    {"name": "expected_date", "type": "DATE"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'draft'"},
                    {"name": "subtotal", "type": "DECIMAL(15,2)"},
                    {"name": "tax_amount", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "shipping_cost", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "total_amount", "type": "DECIMAL(15,2)"},
                    {"name": "currency", "type": "VARCHAR(3)", "default": "'USD'"},
                    {"name": "notes", "type": "TEXT"},
                    {"name": "approved_by", "type": "INTEGER"},
                ],
            },
            {
                "name": "purchase_order_lines",
                "columns": [
                    {"name": "po_line_id", "type": "SERIAL", "primary_key": True},
                    {"name": "po_id", "type": "INTEGER", "not_null": True, "fk": "purchase_orders.po_id"},
                    {"name": "product_id", "type": "INTEGER", "not_null": True},
                    {"name": "quantity_ordered", "type": "INTEGER", "not_null": True},
                    {"name": "quantity_received", "type": "INTEGER", "default": "0"},
                    {"name": "unit_cost", "type": "DECIMAL(15,4)", "not_null": True},
                    {"name": "line_total", "type": "DECIMAL(15,2)"},
                ],
            },
            {
                "name": "receiving_orders",
                "columns": [
                    {"name": "receiving_id", "type": "SERIAL", "primary_key": True},
                    {"name": "receiving_number", "type": "VARCHAR(50)", "unique": True},
                    {"name": "po_id", "type": "INTEGER", "fk": "purchase_orders.po_id"},
                    {"name": "warehouse_id", "type": "INTEGER", "not_null": True, "fk": "warehouses.warehouse_id"},
                    {"name": "received_date", "type": "TIMESTAMP", "not_null": True},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'pending'"},
                    {"name": "received_by", "type": "INTEGER"},
                    {"name": "notes", "type": "TEXT"},
                ],
            },
            {
                "name": "receiving_lines",
                "columns": [
                    {"name": "receiving_line_id", "type": "SERIAL", "primary_key": True},
                    {"name": "receiving_id", "type": "INTEGER", "not_null": True, "fk": "receiving_orders.receiving_id"},
                    {"name": "po_line_id", "type": "INTEGER", "fk": "purchase_order_lines.po_line_id"},
                    {"name": "product_id", "type": "INTEGER", "not_null": True},
                    {"name": "quantity_received", "type": "INTEGER", "not_null": True},
                    {"name": "quantity_accepted", "type": "INTEGER"},
                    {"name": "quantity_rejected", "type": "INTEGER", "default": "0"},
                    {"name": "location_id", "type": "INTEGER", "fk": "storage_locations.location_id"},
                    {"name": "lot_number", "type": "VARCHAR(100)"},
                ],
            },
            {
                "name": "stock_transfers",
                "columns": [
                    {"name": "transfer_id", "type": "SERIAL", "primary_key": True},
                    {"name": "transfer_number", "type": "VARCHAR(50)", "unique": True},
                    {"name": "from_warehouse_id", "type": "INTEGER", "not_null": True, "fk": "warehouses.warehouse_id"},
                    {"name": "to_warehouse_id", "type": "INTEGER", "not_null": True, "fk": "warehouses.warehouse_id"},
                    {"name": "transfer_date", "type": "DATE"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'pending'"},
                    {"name": "requested_by", "type": "INTEGER"},
                    {"name": "approved_by", "type": "INTEGER"},
                    {"name": "notes", "type": "TEXT"},
                ],
            },
            {
                "name": "stock_transfer_lines",
                "columns": [
                    {"name": "transfer_line_id", "type": "SERIAL", "primary_key": True},
                    {"name": "transfer_id", "type": "INTEGER", "not_null": True, "fk": "stock_transfers.transfer_id"},
                    {"name": "product_id", "type": "INTEGER", "not_null": True},
                    {"name": "quantity", "type": "INTEGER", "not_null": True},
                    {"name": "from_location_id", "type": "INTEGER", "fk": "storage_locations.location_id"},
                    {"name": "to_location_id", "type": "INTEGER", "fk": "storage_locations.location_id"},
                ],
            },
            {
                "name": "inventory_counts",
                "columns": [
                    {"name": "count_id", "type": "SERIAL", "primary_key": True},
                    {"name": "count_number", "type": "VARCHAR(50)", "unique": True},
                    {"name": "warehouse_id", "type": "INTEGER", "not_null": True, "fk": "warehouses.warehouse_id"},
                    {"name": "count_date", "type": "DATE", "not_null": True},
                    {"name": "count_type", "type": "VARCHAR(50)"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'planned'"},
                    {"name": "started_at", "type": "TIMESTAMP"},
                    {"name": "completed_at", "type": "TIMESTAMP"},
                    {"name": "performed_by", "type": "INTEGER"},
                ],
            },
            {
                "name": "inventory_count_lines",
                "columns": [
                    {"name": "count_line_id", "type": "SERIAL", "primary_key": True},
                    {"name": "count_id", "type": "INTEGER", "not_null": True, "fk": "inventory_counts.count_id"},
                    {"name": "inventory_id", "type": "INTEGER", "not_null": True, "fk": "inventory_items.inventory_id"},
                    {"name": "expected_quantity", "type": "INTEGER"},
                    {"name": "counted_quantity", "type": "INTEGER"},
                    {"name": "variance", "type": "INTEGER"},
                    {"name": "counted_by", "type": "INTEGER"},
                    {"name": "counted_at", "type": "TIMESTAMP"},
                ],
            },
            {
                "name": "inventory_adjustments",
                "columns": [
                    {"name": "adjustment_id", "type": "SERIAL", "primary_key": True},
                    {"name": "adjustment_number", "type": "VARCHAR(50)", "unique": True},
                    {"name": "warehouse_id", "type": "INTEGER", "not_null": True, "fk": "warehouses.warehouse_id"},
                    {"name": "adjustment_date", "type": "DATE", "not_null": True},
                    {"name": "reason", "type": "VARCHAR(200)"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'pending'"},
                    {"name": "approved_by", "type": "INTEGER"},
                    {"name": "total_value_change", "type": "DECIMAL(15,2)"},
                ],
            },
            {
                "name": "adjustment_lines",
                "columns": [
                    {"name": "adjustment_line_id", "type": "SERIAL", "primary_key": True},
                    {"name": "adjustment_id", "type": "INTEGER", "not_null": True, "fk": "inventory_adjustments.adjustment_id"},
                    {"name": "inventory_id", "type": "INTEGER", "not_null": True, "fk": "inventory_items.inventory_id"},
                    {"name": "quantity_change", "type": "INTEGER", "not_null": True},
                    {"name": "unit_cost", "type": "DECIMAL(15,4)"},
                    {"name": "reason", "type": "VARCHAR(200)"},
                ],
            },
            {
                "name": "pick_orders",
                "columns": [
                    {"name": "pick_id", "type": "SERIAL", "primary_key": True},
                    {"name": "pick_number", "type": "VARCHAR(50)", "unique": True},
                    {"name": "warehouse_id", "type": "INTEGER", "not_null": True, "fk": "warehouses.warehouse_id"},
                    {"name": "order_id", "type": "INTEGER"},
                    {"name": "priority", "type": "INTEGER", "default": "0"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'pending'"},
                    {"name": "assigned_to", "type": "INTEGER"},
                    {"name": "started_at", "type": "TIMESTAMP"},
                    {"name": "completed_at", "type": "TIMESTAMP"},
                ],
            },
            {
                "name": "pick_lines",
                "columns": [
                    {"name": "pick_line_id", "type": "SERIAL", "primary_key": True},
                    {"name": "pick_id", "type": "INTEGER", "not_null": True, "fk": "pick_orders.pick_id"},
                    {"name": "inventory_id", "type": "INTEGER", "not_null": True, "fk": "inventory_items.inventory_id"},
                    {"name": "location_id", "type": "INTEGER", "fk": "storage_locations.location_id"},
                    {"name": "quantity_requested", "type": "INTEGER", "not_null": True},
                    {"name": "quantity_picked", "type": "INTEGER", "default": "0"},
                    {"name": "picked_at", "type": "TIMESTAMP"},
                ],
            },
            {
                "name": "pack_orders",
                "columns": [
                    {"name": "pack_id", "type": "SERIAL", "primary_key": True},
                    {"name": "pack_number", "type": "VARCHAR(50)", "unique": True},
                    {"name": "pick_id", "type": "INTEGER", "fk": "pick_orders.pick_id"},
                    {"name": "order_id", "type": "INTEGER"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'pending'"},
                    {"name": "packed_by", "type": "INTEGER"},
                    {"name": "packed_at", "type": "TIMESTAMP"},
                    {"name": "total_weight_kg", "type": "DECIMAL(10,3)"},
                    {"name": "num_packages", "type": "INTEGER"},
                ],
            },
            {
                "name": "packages",
                "columns": [
                    {"name": "package_id", "type": "SERIAL", "primary_key": True},
                    {"name": "pack_id", "type": "INTEGER", "not_null": True, "fk": "pack_orders.pack_id"},
                    {"name": "package_number", "type": "INTEGER", "not_null": True},
                    {"name": "weight_kg", "type": "DECIMAL(10,3)"},
                    {"name": "length_cm", "type": "DECIMAL(8,2)"},
                    {"name": "width_cm", "type": "DECIMAL(8,2)"},
                    {"name": "height_cm", "type": "DECIMAL(8,2)"},
                    {"name": "tracking_number", "type": "VARCHAR(100)"},
                ],
            },
            {
                "name": "abc_analysis",
                "columns": [
                    {"name": "analysis_id", "type": "SERIAL", "primary_key": True},
                    {"name": "product_id", "type": "INTEGER", "not_null": True},
                    {"name": "warehouse_id", "type": "INTEGER", "fk": "warehouses.warehouse_id"},
                    {"name": "analysis_date", "type": "DATE", "not_null": True},
                    {"name": "classification", "type": "VARCHAR(1)"},
                    {"name": "annual_usage_value", "type": "DECIMAL(15,2)"},
                    {"name": "cumulative_percentage", "type": "DECIMAL(6,3)"},
                ],
            },
            {
                "name": "reorder_rules",
                "columns": [
                    {"name": "rule_id", "type": "SERIAL", "primary_key": True},
                    {"name": "product_id", "type": "INTEGER", "not_null": True},
                    {"name": "warehouse_id", "type": "INTEGER", "fk": "warehouses.warehouse_id"},
                    {"name": "reorder_point", "type": "INTEGER", "not_null": True},
                    {"name": "reorder_quantity", "type": "INTEGER", "not_null": True},
                    {"name": "safety_stock", "type": "INTEGER", "default": "0"},
                    {"name": "max_stock", "type": "INTEGER"},
                    {"name": "lead_time_days", "type": "INTEGER"},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                ],
            },
        ],
    },
    # ═══════════════════════════════════════════════════════════════════════════
    # CRM & SALES (30 tables)
    # ═══════════════════════════════════════════════════════════════════════════
    "crm": {
        "description": "Customer Relationship Management and Sales",
        "tables": [
            {
                "name": "accounts",
                "columns": [
                    {"name": "account_id", "type": "SERIAL", "primary_key": True},
                    {"name": "account_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "account_type", "type": "VARCHAR(50)"},
                    {"name": "industry", "type": "VARCHAR(100)"},
                    {"name": "website", "type": "VARCHAR(255)"},
                    {"name": "phone", "type": "VARCHAR(20)"},
                    {"name": "fax", "type": "VARCHAR(20)"},
                    {"name": "employees_count", "type": "INTEGER"},
                    {"name": "annual_revenue", "type": "DECIMAL(15,2)"},
                    {"name": "billing_address", "type": "TEXT"},
                    {"name": "shipping_address", "type": "TEXT"},
                    {"name": "description", "type": "TEXT"},
                    {"name": "owner_id", "type": "INTEGER"},
                    {"name": "parent_account_id", "type": "INTEGER", "fk": "accounts.account_id"},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                ],
            },
            {
                "name": "contacts",
                "columns": [
                    {"name": "contact_id", "type": "SERIAL", "primary_key": True},
                    {"name": "account_id", "type": "INTEGER", "fk": "accounts.account_id"},
                    {"name": "first_name", "type": "VARCHAR(100)"},
                    {"name": "last_name", "type": "VARCHAR(100)", "not_null": True},
                    {"name": "email", "type": "VARCHAR(255)"},
                    {"name": "phone", "type": "VARCHAR(20)"},
                    {"name": "mobile", "type": "VARCHAR(20)"},
                    {"name": "title", "type": "VARCHAR(100)"},
                    {"name": "department", "type": "VARCHAR(100)"},
                    {"name": "mailing_address", "type": "TEXT"},
                    {"name": "description", "type": "TEXT"},
                    {"name": "owner_id", "type": "INTEGER"},
                    {"name": "lead_source", "type": "VARCHAR(100)"},
                    {"name": "do_not_call", "type": "BOOLEAN", "default": "false"},
                    {"name": "do_not_email", "type": "BOOLEAN", "default": "false"},
                ],
            },
            {
                "name": "leads",
                "columns": [
                    {"name": "lead_id", "type": "SERIAL", "primary_key": True},
                    {"name": "first_name", "type": "VARCHAR(100)"},
                    {"name": "last_name", "type": "VARCHAR(100)", "not_null": True},
                    {"name": "company", "type": "VARCHAR(200)"},
                    {"name": "title", "type": "VARCHAR(100)"},
                    {"name": "email", "type": "VARCHAR(255)"},
                    {"name": "phone", "type": "VARCHAR(20)"},
                    {"name": "website", "type": "VARCHAR(255)"},
                    {"name": "lead_source", "type": "VARCHAR(100)"},
                    {"name": "lead_status", "type": "VARCHAR(50)", "default": "'new'"},
                    {"name": "rating", "type": "VARCHAR(20)"},
                    {"name": "industry", "type": "VARCHAR(100)"},
                    {"name": "annual_revenue", "type": "DECIMAL(15,2)"},
                    {"name": "employees", "type": "INTEGER"},
                    {"name": "description", "type": "TEXT"},
                    {"name": "address", "type": "TEXT"},
                    {"name": "owner_id", "type": "INTEGER"},
                    {"name": "converted_account_id", "type": "INTEGER", "fk": "accounts.account_id"},
                    {"name": "converted_contact_id", "type": "INTEGER", "fk": "contacts.contact_id"},
                    {"name": "converted_date", "type": "DATE"},
                ],
            },
            {
                "name": "opportunities",
                "columns": [
                    {"name": "opportunity_id", "type": "SERIAL", "primary_key": True},
                    {"name": "opportunity_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "account_id", "type": "INTEGER", "fk": "accounts.account_id"},
                    {"name": "contact_id", "type": "INTEGER", "fk": "contacts.contact_id"},
                    {"name": "stage", "type": "VARCHAR(50)"},
                    {"name": "amount", "type": "DECIMAL(15,2)"},
                    {"name": "probability", "type": "INTEGER"},
                    {"name": "expected_revenue", "type": "DECIMAL(15,2)"},
                    {"name": "close_date", "type": "DATE"},
                    {"name": "type", "type": "VARCHAR(50)"},
                    {"name": "lead_source", "type": "VARCHAR(100)"},
                    {"name": "next_step", "type": "VARCHAR(500)"},
                    {"name": "description", "type": "TEXT"},
                    {"name": "owner_id", "type": "INTEGER"},
                    {"name": "campaign_id", "type": "INTEGER", "fk": "campaigns.campaign_id"},
                    {"name": "is_won", "type": "BOOLEAN"},
                    {"name": "is_closed", "type": "BOOLEAN", "default": "false"},
                ],
            },
            {
                "name": "opportunity_stages",
                "columns": [
                    {"name": "stage_id", "type": "SERIAL", "primary_key": True},
                    {"name": "stage_name", "type": "VARCHAR(100)", "not_null": True},
                    {"name": "probability", "type": "INTEGER"},
                    {"name": "sort_order", "type": "INTEGER"},
                    {"name": "is_closed", "type": "BOOLEAN", "default": "false"},
                    {"name": "is_won", "type": "BOOLEAN", "default": "false"},
                ],
            },
            {
                "name": "opportunity_products",
                "columns": [
                    {"name": "op_product_id", "type": "SERIAL", "primary_key": True},
                    {"name": "opportunity_id", "type": "INTEGER", "not_null": True, "fk": "opportunities.opportunity_id"},
                    {"name": "product_id", "type": "INTEGER"},
                    {"name": "product_name", "type": "VARCHAR(200)"},
                    {"name": "quantity", "type": "DECIMAL(10,2)"},
                    {"name": "unit_price", "type": "DECIMAL(15,2)"},
                    {"name": "discount", "type": "DECIMAL(5,2)", "default": "0"},
                    {"name": "total_price", "type": "DECIMAL(15,2)"},
                    {"name": "description", "type": "TEXT"},
                ],
            },
            {
                "name": "quotes",
                "columns": [
                    {"name": "quote_id", "type": "SERIAL", "primary_key": True},
                    {"name": "quote_number", "type": "VARCHAR(50)", "unique": True},
                    {"name": "opportunity_id", "type": "INTEGER", "fk": "opportunities.opportunity_id"},
                    {"name": "account_id", "type": "INTEGER", "fk": "accounts.account_id"},
                    {"name": "contact_id", "type": "INTEGER", "fk": "contacts.contact_id"},
                    {"name": "quote_name", "type": "VARCHAR(200)"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'draft'"},
                    {"name": "expiration_date", "type": "DATE"},
                    {"name": "subtotal", "type": "DECIMAL(15,2)"},
                    {"name": "discount", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "tax", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "shipping", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "grand_total", "type": "DECIMAL(15,2)"},
                    {"name": "billing_address", "type": "TEXT"},
                    {"name": "shipping_address", "type": "TEXT"},
                    {"name": "description", "type": "TEXT"},
                    {"name": "owner_id", "type": "INTEGER"},
                ],
            },
            {
                "name": "quote_lines",
                "columns": [
                    {"name": "quote_line_id", "type": "SERIAL", "primary_key": True},
                    {"name": "quote_id", "type": "INTEGER", "not_null": True, "fk": "quotes.quote_id"},
                    {"name": "product_id", "type": "INTEGER"},
                    {"name": "product_name", "type": "VARCHAR(200)"},
                    {"name": "quantity", "type": "DECIMAL(10,2)", "not_null": True},
                    {"name": "unit_price", "type": "DECIMAL(15,2)", "not_null": True},
                    {"name": "discount", "type": "DECIMAL(5,2)", "default": "0"},
                    {"name": "line_total", "type": "DECIMAL(15,2)"},
                    {"name": "description", "type": "TEXT"},
                    {"name": "sort_order", "type": "INTEGER"},
                ],
            },
            {
                "name": "sales_orders",
                "columns": [
                    {"name": "sales_order_id", "type": "SERIAL", "primary_key": True},
                    {"name": "order_number", "type": "VARCHAR(50)", "not_null": True, "unique": True},
                    {"name": "quote_id", "type": "INTEGER", "fk": "quotes.quote_id"},
                    {"name": "opportunity_id", "type": "INTEGER", "fk": "opportunities.opportunity_id"},
                    {"name": "account_id", "type": "INTEGER", "fk": "accounts.account_id"},
                    {"name": "contact_id", "type": "INTEGER", "fk": "contacts.contact_id"},
                    {"name": "order_date", "type": "DATE", "not_null": True},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'pending'"},
                    {"name": "subtotal", "type": "DECIMAL(15,2)"},
                    {"name": "discount", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "tax", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "shipping", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "grand_total", "type": "DECIMAL(15,2)"},
                    {"name": "billing_address", "type": "TEXT"},
                    {"name": "shipping_address", "type": "TEXT"},
                    {"name": "owner_id", "type": "INTEGER"},
                ],
            },
            {
                "name": "sales_order_lines",
                "columns": [
                    {"name": "so_line_id", "type": "SERIAL", "primary_key": True},
                    {"name": "sales_order_id", "type": "INTEGER", "not_null": True, "fk": "sales_orders.sales_order_id"},
                    {"name": "product_id", "type": "INTEGER"},
                    {"name": "product_name", "type": "VARCHAR(200)"},
                    {"name": "quantity", "type": "DECIMAL(10,2)", "not_null": True},
                    {"name": "unit_price", "type": "DECIMAL(15,2)", "not_null": True},
                    {"name": "discount", "type": "DECIMAL(5,2)", "default": "0"},
                    {"name": "line_total", "type": "DECIMAL(15,2)"},
                ],
            },
            {
                "name": "activities",
                "columns": [
                    {"name": "activity_id", "type": "SERIAL", "primary_key": True},
                    {"name": "activity_type", "type": "VARCHAR(50)", "not_null": True},
                    {"name": "subject", "type": "VARCHAR(500)", "not_null": True},
                    {"name": "description", "type": "TEXT"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'planned'"},
                    {"name": "priority", "type": "VARCHAR(20)"},
                    {"name": "due_date", "type": "TIMESTAMP"},
                    {"name": "completed_date", "type": "TIMESTAMP"},
                    {"name": "related_to_type", "type": "VARCHAR(50)"},
                    {"name": "related_to_id", "type": "INTEGER"},
                    {"name": "owner_id", "type": "INTEGER"},
                    {"name": "assigned_to", "type": "INTEGER"},
                ],
            },
            {
                "name": "tasks",
                "columns": [
                    {"name": "task_id", "type": "SERIAL", "primary_key": True},
                    {"name": "subject", "type": "VARCHAR(500)", "not_null": True},
                    {"name": "description", "type": "TEXT"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'not_started'"},
                    {"name": "priority", "type": "VARCHAR(20)"},
                    {"name": "due_date", "type": "DATE"},
                    {"name": "reminder_date", "type": "TIMESTAMP"},
                    {"name": "related_to_type", "type": "VARCHAR(50)"},
                    {"name": "related_to_id", "type": "INTEGER"},
                    {"name": "owner_id", "type": "INTEGER"},
                    {"name": "assigned_to", "type": "INTEGER"},
                ],
            },
            {
                "name": "events",
                "columns": [
                    {"name": "event_id", "type": "SERIAL", "primary_key": True},
                    {"name": "subject", "type": "VARCHAR(500)", "not_null": True},
                    {"name": "description", "type": "TEXT"},
                    {"name": "location", "type": "VARCHAR(500)"},
                    {"name": "start_date", "type": "TIMESTAMP", "not_null": True},
                    {"name": "end_date", "type": "TIMESTAMP"},
                    {"name": "is_all_day", "type": "BOOLEAN", "default": "false"},
                    {"name": "related_to_type", "type": "VARCHAR(50)"},
                    {"name": "related_to_id", "type": "INTEGER"},
                    {"name": "owner_id", "type": "INTEGER"},
                ],
            },
            {
                "name": "event_attendees",
                "columns": [
                    {"name": "attendee_id", "type": "SERIAL", "primary_key": True},
                    {"name": "event_id", "type": "INTEGER", "not_null": True, "fk": "events.event_id"},
                    {"name": "contact_id", "type": "INTEGER", "fk": "contacts.contact_id"},
                    {"name": "user_id", "type": "INTEGER"},
                    {"name": "email", "type": "VARCHAR(255)"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'pending'"},
                ],
            },
            {
                "name": "call_logs",
                "columns": [
                    {"name": "call_id", "type": "SERIAL", "primary_key": True},
                    {"name": "subject", "type": "VARCHAR(500)"},
                    {"name": "call_type", "type": "VARCHAR(50)"},
                    {"name": "call_result", "type": "VARCHAR(50)"},
                    {"name": "call_date", "type": "TIMESTAMP", "not_null": True},
                    {"name": "duration_minutes", "type": "INTEGER"},
                    {"name": "description", "type": "TEXT"},
                    {"name": "related_to_type", "type": "VARCHAR(50)"},
                    {"name": "related_to_id", "type": "INTEGER"},
                    {"name": "owner_id", "type": "INTEGER"},
                ],
            },
            {
                "name": "campaigns",
                "columns": [
                    {"name": "campaign_id", "type": "SERIAL", "primary_key": True},
                    {"name": "campaign_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "campaign_type", "type": "VARCHAR(50)"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'planned'"},
                    {"name": "start_date", "type": "DATE"},
                    {"name": "end_date", "type": "DATE"},
                    {"name": "budgeted_cost", "type": "DECIMAL(15,2)"},
                    {"name": "actual_cost", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "expected_revenue", "type": "DECIMAL(15,2)"},
                    {"name": "expected_response", "type": "INTEGER"},
                    {"name": "num_sent", "type": "INTEGER", "default": "0"},
                    {"name": "num_responses", "type": "INTEGER", "default": "0"},
                    {"name": "description", "type": "TEXT"},
                    {"name": "owner_id", "type": "INTEGER"},
                ],
            },
            {
                "name": "campaign_members",
                "columns": [
                    {"name": "member_id", "type": "SERIAL", "primary_key": True},
                    {"name": "campaign_id", "type": "INTEGER", "not_null": True, "fk": "campaigns.campaign_id"},
                    {"name": "lead_id", "type": "INTEGER", "fk": "leads.lead_id"},
                    {"name": "contact_id", "type": "INTEGER", "fk": "contacts.contact_id"},
                    {"name": "status", "type": "VARCHAR(50)"},
                    {"name": "responded_date", "type": "DATE"},
                    {"name": "first_responded_date", "type": "DATE"},
                ],
            },
            {
                "name": "territories",
                "columns": [
                    {"name": "territory_id", "type": "SERIAL", "primary_key": True},
                    {"name": "territory_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "parent_territory_id", "type": "INTEGER", "fk": "territories.territory_id"},
                    {"name": "description", "type": "TEXT"},
                ],
            },
            {
                "name": "territory_assignments",
                "columns": [
                    {"name": "assignment_id", "type": "SERIAL", "primary_key": True},
                    {"name": "territory_id", "type": "INTEGER", "not_null": True, "fk": "territories.territory_id"},
                    {"name": "user_id", "type": "INTEGER"},
                    {"name": "account_id", "type": "INTEGER", "fk": "accounts.account_id"},
                    {"name": "assignment_type", "type": "VARCHAR(50)"},
                ],
            },
            {
                "name": "sales_teams",
                "columns": [
                    {"name": "team_id", "type": "SERIAL", "primary_key": True},
                    {"name": "team_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "description", "type": "TEXT"},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                ],
            },
            {
                "name": "team_members",
                "columns": [
                    {"name": "team_member_id", "type": "SERIAL", "primary_key": True},
                    {"name": "team_id", "type": "INTEGER", "not_null": True, "fk": "sales_teams.team_id"},
                    {"name": "user_id", "type": "INTEGER", "not_null": True},
                    {"name": "role", "type": "VARCHAR(100)"},
                    {"name": "is_leader", "type": "BOOLEAN", "default": "false"},
                ],
            },
            {
                "name": "forecasts",
                "columns": [
                    {"name": "forecast_id", "type": "SERIAL", "primary_key": True},
                    {"name": "user_id", "type": "INTEGER"},
                    {"name": "forecast_period", "type": "VARCHAR(20)"},
                    {"name": "forecast_year", "type": "INTEGER"},
                    {"name": "quota_amount", "type": "DECIMAL(15,2)"},
                    {"name": "forecast_amount", "type": "DECIMAL(15,2)"},
                    {"name": "closed_amount", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "pipeline_amount", "type": "DECIMAL(15,2)", "default": "0"},
                ],
            },
            {
                "name": "price_books",
                "columns": [
                    {"name": "price_book_id", "type": "SERIAL", "primary_key": True},
                    {"name": "price_book_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "description", "type": "TEXT"},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                    {"name": "is_standard", "type": "BOOLEAN", "default": "false"},
                ],
            },
            {
                "name": "price_book_entries",
                "columns": [
                    {"name": "entry_id", "type": "SERIAL", "primary_key": True},
                    {"name": "price_book_id", "type": "INTEGER", "not_null": True, "fk": "price_books.price_book_id"},
                    {"name": "product_id", "type": "INTEGER", "not_null": True},
                    {"name": "unit_price", "type": "DECIMAL(15,2)", "not_null": True},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                ],
            },
            {
                "name": "contracts",
                "columns": [
                    {"name": "contract_id", "type": "SERIAL", "primary_key": True},
                    {"name": "contract_number", "type": "VARCHAR(50)", "unique": True},
                    {"name": "account_id", "type": "INTEGER", "fk": "accounts.account_id"},
                    {"name": "contract_name", "type": "VARCHAR(200)"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'draft'"},
                    {"name": "start_date", "type": "DATE"},
                    {"name": "end_date", "type": "DATE"},
                    {"name": "contract_term", "type": "INTEGER"},
                    {"name": "contract_value", "type": "DECIMAL(15,2)"},
                    {"name": "billing_frequency", "type": "VARCHAR(50)"},
                    {"name": "description", "type": "TEXT"},
                    {"name": "owner_id", "type": "INTEGER"},
                    {"name": "signed_date", "type": "DATE"},
                ],
            },
            {
                "name": "cases",
                "columns": [
                    {"name": "case_id", "type": "SERIAL", "primary_key": True},
                    {"name": "case_number", "type": "VARCHAR(50)", "unique": True},
                    {"name": "account_id", "type": "INTEGER", "fk": "accounts.account_id"},
                    {"name": "contact_id", "type": "INTEGER", "fk": "contacts.contact_id"},
                    {"name": "subject", "type": "VARCHAR(500)", "not_null": True},
                    {"name": "description", "type": "TEXT"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'new'"},
                    {"name": "priority", "type": "VARCHAR(20)"},
                    {"name": "type", "type": "VARCHAR(100)"},
                    {"name": "reason", "type": "VARCHAR(200)"},
                    {"name": "origin", "type": "VARCHAR(100)"},
                    {"name": "owner_id", "type": "INTEGER"},
                    {"name": "closed_date", "type": "TIMESTAMP"},
                ],
            },
            {
                "name": "case_comments",
                "columns": [
                    {"name": "comment_id", "type": "SERIAL", "primary_key": True},
                    {"name": "case_id", "type": "INTEGER", "not_null": True, "fk": "cases.case_id"},
                    {"name": "comment_body", "type": "TEXT", "not_null": True},
                    {"name": "is_public", "type": "BOOLEAN", "default": "false"},
                    {"name": "author_id", "type": "INTEGER"},
                ],
            },
            {
                "name": "solutions",
                "columns": [
                    {"name": "solution_id", "type": "SERIAL", "primary_key": True},
                    {"name": "solution_title", "type": "VARCHAR(500)", "not_null": True},
                    {"name": "solution_body", "type": "TEXT"},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'draft'"},
                    {"name": "is_published", "type": "BOOLEAN", "default": "false"},
                    {"name": "times_used", "type": "INTEGER", "default": "0"},
                ],
            },
            {
                "name": "case_solutions",
                "columns": [
                    {"name": "case_solution_id", "type": "SERIAL", "primary_key": True},
                    {"name": "case_id", "type": "INTEGER", "not_null": True, "fk": "cases.case_id"},
                    {"name": "solution_id", "type": "INTEGER", "not_null": True, "fk": "solutions.solution_id"},
                ],
            },
        ],
    },
}

