"""
Domain definitions for synthetic 250-table database generator.
Each domain includes table templates with columns, types, and relationships.
"""

from typing import Dict, List, Any

# Common timestamp columns
TIMESTAMPS = [
    {"name": "created_at", "type": "TIMESTAMP", "default": "CURRENT_TIMESTAMP"},
    {"name": "updated_at", "type": "TIMESTAMP", "default": "CURRENT_TIMESTAMP"},
]

DOMAINS: Dict[str, Dict[str, Any]] = {
    # ═══════════════════════════════════════════════════════════════════════════
    # HUMAN RESOURCES (25 tables)
    # ═══════════════════════════════════════════════════════════════════════════
    "hr": {
        "description": "Human Resources Management",
        "tables": [
            {
                "name": "employees",
                "columns": [
                    {"name": "employee_id", "type": "SERIAL", "primary_key": True},
                    {"name": "first_name", "type": "VARCHAR(100)", "not_null": True},
                    {"name": "last_name", "type": "VARCHAR(100)", "not_null": True},
                    {"name": "email", "type": "VARCHAR(255)", "unique": True},
                    {"name": "phone", "type": "VARCHAR(20)"},
                    {"name": "hire_date", "type": "DATE", "not_null": True},
                    {"name": "termination_date", "type": "DATE"},
                    {"name": "birth_date", "type": "DATE"},
                    {"name": "gender", "type": "VARCHAR(10)"},
                    {"name": "salary", "type": "DECIMAL(15,2)"},
                    {"name": "department_id", "type": "INTEGER", "fk": "departments.department_id"},
                    {"name": "manager_id", "type": "INTEGER", "fk": "employees.employee_id"},
                    {"name": "job_title_id", "type": "INTEGER", "fk": "job_titles.job_title_id"},
                    {"name": "employment_status", "type": "VARCHAR(20)", "default": "'active'"},
                ],
            },
            {
                "name": "departments",
                "columns": [
                    {"name": "department_id", "type": "SERIAL", "primary_key": True},
                    {"name": "department_name", "type": "VARCHAR(100)", "not_null": True, "unique": True},
                    {"name": "department_code", "type": "VARCHAR(20)", "unique": True},
                    {"name": "description", "type": "TEXT"},
                    {"name": "parent_department_id", "type": "INTEGER", "fk": "departments.department_id"},
                    {"name": "cost_center", "type": "VARCHAR(20)"},
                    {"name": "location_id", "type": "INTEGER", "fk": "office_locations.location_id"},
                ],
            },
            {
                "name": "job_titles",
                "columns": [
                    {"name": "job_title_id", "type": "SERIAL", "primary_key": True},
                    {"name": "title", "type": "VARCHAR(100)", "not_null": True},
                    {"name": "job_family", "type": "VARCHAR(50)"},
                    {"name": "job_level", "type": "INTEGER"},
                    {"name": "min_salary", "type": "DECIMAL(15,2)"},
                    {"name": "max_salary", "type": "DECIMAL(15,2)"},
                    {"name": "description", "type": "TEXT"},
                ],
            },
            {
                "name": "office_locations",
                "columns": [
                    {"name": "location_id", "type": "SERIAL", "primary_key": True},
                    {"name": "location_name", "type": "VARCHAR(100)", "not_null": True},
                    {"name": "address_line1", "type": "VARCHAR(255)"},
                    {"name": "address_line2", "type": "VARCHAR(255)"},
                    {"name": "city", "type": "VARCHAR(100)"},
                    {"name": "state_province", "type": "VARCHAR(100)"},
                    {"name": "postal_code", "type": "VARCHAR(20)"},
                    {"name": "country_code", "type": "VARCHAR(3)"},
                    {"name": "timezone", "type": "VARCHAR(50)"},
                    {"name": "is_headquarters", "type": "BOOLEAN", "default": "false"},
                ],
            },
            {
                "name": "salary_history",
                "columns": [
                    {"name": "salary_history_id", "type": "SERIAL", "primary_key": True},
                    {"name": "employee_id", "type": "INTEGER", "not_null": True, "fk": "employees.employee_id"},
                    {"name": "effective_date", "type": "DATE", "not_null": True},
                    {"name": "end_date", "type": "DATE"},
                    {"name": "salary_amount", "type": "DECIMAL(15,2)", "not_null": True},
                    {"name": "currency", "type": "VARCHAR(3)", "default": "'USD'"},
                    {"name": "change_reason", "type": "VARCHAR(100)"},
                    {"name": "approved_by", "type": "INTEGER", "fk": "employees.employee_id"},
                ],
            },
            {
                "name": "benefits_plans",
                "columns": [
                    {"name": "plan_id", "type": "SERIAL", "primary_key": True},
                    {"name": "plan_name", "type": "VARCHAR(100)", "not_null": True},
                    {"name": "plan_type", "type": "VARCHAR(50)"},
                    {"name": "provider_name", "type": "VARCHAR(100)"},
                    {"name": "coverage_details", "type": "JSONB"},
                    {"name": "monthly_cost_employee", "type": "DECIMAL(10,2)"},
                    {"name": "monthly_cost_employer", "type": "DECIMAL(10,2)"},
                    {"name": "effective_date", "type": "DATE"},
                    {"name": "termination_date", "type": "DATE"},
                ],
            },
            {
                "name": "employee_benefits",
                "columns": [
                    {"name": "enrollment_id", "type": "SERIAL", "primary_key": True},
                    {"name": "employee_id", "type": "INTEGER", "not_null": True, "fk": "employees.employee_id"},
                    {"name": "plan_id", "type": "INTEGER", "not_null": True, "fk": "benefits_plans.plan_id"},
                    {"name": "enrollment_date", "type": "DATE", "not_null": True},
                    {"name": "coverage_level", "type": "VARCHAR(50)"},
                    {"name": "dependents_count", "type": "INTEGER", "default": "0"},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                ],
            },
            {
                "name": "time_off_requests",
                "columns": [
                    {"name": "request_id", "type": "SERIAL", "primary_key": True},
                    {"name": "employee_id", "type": "INTEGER", "not_null": True, "fk": "employees.employee_id"},
                    {"name": "request_type", "type": "VARCHAR(50)", "not_null": True},
                    {"name": "start_date", "type": "DATE", "not_null": True},
                    {"name": "end_date", "type": "DATE", "not_null": True},
                    {"name": "hours_requested", "type": "DECIMAL(5,2)"},
                    {"name": "status", "type": "VARCHAR(20)", "default": "'pending'"},
                    {"name": "approved_by", "type": "INTEGER", "fk": "employees.employee_id"},
                    {"name": "notes", "type": "TEXT"},
                ],
            },
            {
                "name": "time_off_balances",
                "columns": [
                    {"name": "balance_id", "type": "SERIAL", "primary_key": True},
                    {"name": "employee_id", "type": "INTEGER", "not_null": True, "fk": "employees.employee_id"},
                    {"name": "leave_type", "type": "VARCHAR(50)", "not_null": True},
                    {"name": "fiscal_year", "type": "INTEGER", "not_null": True},
                    {"name": "hours_accrued", "type": "DECIMAL(6,2)", "default": "0"},
                    {"name": "hours_used", "type": "DECIMAL(6,2)", "default": "0"},
                    {"name": "hours_carried_over", "type": "DECIMAL(6,2)", "default": "0"},
                ],
            },
            {
                "name": "performance_reviews",
                "columns": [
                    {"name": "review_id", "type": "SERIAL", "primary_key": True},
                    {"name": "employee_id", "type": "INTEGER", "not_null": True, "fk": "employees.employee_id"},
                    {"name": "reviewer_id", "type": "INTEGER", "not_null": True, "fk": "employees.employee_id"},
                    {"name": "review_period_start", "type": "DATE"},
                    {"name": "review_period_end", "type": "DATE"},
                    {"name": "review_date", "type": "DATE"},
                    {"name": "overall_rating", "type": "DECIMAL(3,2)"},
                    {"name": "goals_met_percentage", "type": "INTEGER"},
                    {"name": "comments", "type": "TEXT"},
                    {"name": "status", "type": "VARCHAR(20)", "default": "'draft'"},
                ],
            },
            {
                "name": "performance_goals",
                "columns": [
                    {"name": "goal_id", "type": "SERIAL", "primary_key": True},
                    {"name": "employee_id", "type": "INTEGER", "not_null": True, "fk": "employees.employee_id"},
                    {"name": "goal_title", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "description", "type": "TEXT"},
                    {"name": "category", "type": "VARCHAR(50)"},
                    {"name": "target_date", "type": "DATE"},
                    {"name": "completion_percentage", "type": "INTEGER", "default": "0"},
                    {"name": "status", "type": "VARCHAR(20)", "default": "'active'"},
                    {"name": "weight", "type": "DECIMAL(5,2)"},
                ],
            },
            {
                "name": "training_courses",
                "columns": [
                    {"name": "course_id", "type": "SERIAL", "primary_key": True},
                    {"name": "course_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "course_code", "type": "VARCHAR(50)", "unique": True},
                    {"name": "description", "type": "TEXT"},
                    {"name": "category", "type": "VARCHAR(100)"},
                    {"name": "duration_hours", "type": "DECIMAL(5,2)"},
                    {"name": "is_mandatory", "type": "BOOLEAN", "default": "false"},
                    {"name": "provider", "type": "VARCHAR(100)"},
                    {"name": "cost", "type": "DECIMAL(10,2)"},
                ],
            },
            {
                "name": "employee_training",
                "columns": [
                    {"name": "enrollment_id", "type": "SERIAL", "primary_key": True},
                    {"name": "employee_id", "type": "INTEGER", "not_null": True, "fk": "employees.employee_id"},
                    {"name": "course_id", "type": "INTEGER", "not_null": True, "fk": "training_courses.course_id"},
                    {"name": "enrollment_date", "type": "DATE"},
                    {"name": "completion_date", "type": "DATE"},
                    {"name": "score", "type": "DECIMAL(5,2)"},
                    {"name": "status", "type": "VARCHAR(20)", "default": "'enrolled'"},
                    {"name": "certificate_number", "type": "VARCHAR(50)"},
                ],
            },
            {
                "name": "skills",
                "columns": [
                    {"name": "skill_id", "type": "SERIAL", "primary_key": True},
                    {"name": "skill_name", "type": "VARCHAR(100)", "not_null": True, "unique": True},
                    {"name": "category", "type": "VARCHAR(50)"},
                    {"name": "description", "type": "TEXT"},
                ],
            },
            {
                "name": "employee_skills",
                "columns": [
                    {"name": "employee_skill_id", "type": "SERIAL", "primary_key": True},
                    {"name": "employee_id", "type": "INTEGER", "not_null": True, "fk": "employees.employee_id"},
                    {"name": "skill_id", "type": "INTEGER", "not_null": True, "fk": "skills.skill_id"},
                    {"name": "proficiency_level", "type": "INTEGER"},
                    {"name": "years_experience", "type": "DECIMAL(4,1)"},
                    {"name": "last_used_date", "type": "DATE"},
                    {"name": "is_primary", "type": "BOOLEAN", "default": "false"},
                ],
            },
            {
                "name": "job_postings",
                "columns": [
                    {"name": "posting_id", "type": "SERIAL", "primary_key": True},
                    {"name": "job_title_id", "type": "INTEGER", "fk": "job_titles.job_title_id"},
                    {"name": "department_id", "type": "INTEGER", "fk": "departments.department_id"},
                    {"name": "location_id", "type": "INTEGER", "fk": "office_locations.location_id"},
                    {"name": "posting_title", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "description", "type": "TEXT"},
                    {"name": "requirements", "type": "TEXT"},
                    {"name": "salary_min", "type": "DECIMAL(15,2)"},
                    {"name": "salary_max", "type": "DECIMAL(15,2)"},
                    {"name": "employment_type", "type": "VARCHAR(50)"},
                    {"name": "posted_date", "type": "DATE"},
                    {"name": "closing_date", "type": "DATE"},
                    {"name": "status", "type": "VARCHAR(20)", "default": "'open'"},
                    {"name": "hiring_manager_id", "type": "INTEGER", "fk": "employees.employee_id"},
                ],
            },
            {
                "name": "job_applicants",
                "columns": [
                    {"name": "applicant_id", "type": "SERIAL", "primary_key": True},
                    {"name": "first_name", "type": "VARCHAR(100)", "not_null": True},
                    {"name": "last_name", "type": "VARCHAR(100)", "not_null": True},
                    {"name": "email", "type": "VARCHAR(255)", "not_null": True},
                    {"name": "phone", "type": "VARCHAR(20)"},
                    {"name": "resume_url", "type": "VARCHAR(500)"},
                    {"name": "linkedin_url", "type": "VARCHAR(500)"},
                    {"name": "source", "type": "VARCHAR(100)"},
                ],
            },
            {
                "name": "job_applications",
                "columns": [
                    {"name": "application_id", "type": "SERIAL", "primary_key": True},
                    {"name": "posting_id", "type": "INTEGER", "not_null": True, "fk": "job_postings.posting_id"},
                    {"name": "applicant_id", "type": "INTEGER", "not_null": True, "fk": "job_applicants.applicant_id"},
                    {"name": "application_date", "type": "DATE", "not_null": True},
                    {"name": "status", "type": "VARCHAR(50)", "default": "'new'"},
                    {"name": "cover_letter", "type": "TEXT"},
                    {"name": "notes", "type": "TEXT"},
                ],
            },
            {
                "name": "interviews",
                "columns": [
                    {"name": "interview_id", "type": "SERIAL", "primary_key": True},
                    {"name": "application_id", "type": "INTEGER", "not_null": True, "fk": "job_applications.application_id"},
                    {"name": "interviewer_id", "type": "INTEGER", "not_null": True, "fk": "employees.employee_id"},
                    {"name": "interview_type", "type": "VARCHAR(50)"},
                    {"name": "scheduled_date", "type": "TIMESTAMP"},
                    {"name": "duration_minutes", "type": "INTEGER"},
                    {"name": "location", "type": "VARCHAR(200)"},
                    {"name": "status", "type": "VARCHAR(20)", "default": "'scheduled'"},
                    {"name": "rating", "type": "INTEGER"},
                    {"name": "feedback", "type": "TEXT"},
                ],
            },
            {
                "name": "employee_documents",
                "columns": [
                    {"name": "document_id", "type": "SERIAL", "primary_key": True},
                    {"name": "employee_id", "type": "INTEGER", "not_null": True, "fk": "employees.employee_id"},
                    {"name": "document_type", "type": "VARCHAR(50)", "not_null": True},
                    {"name": "document_name", "type": "VARCHAR(200)"},
                    {"name": "file_path", "type": "VARCHAR(500)"},
                    {"name": "upload_date", "type": "DATE"},
                    {"name": "expiration_date", "type": "DATE"},
                    {"name": "is_verified", "type": "BOOLEAN", "default": "false"},
                ],
            },
            {
                "name": "emergency_contacts",
                "columns": [
                    {"name": "contact_id", "type": "SERIAL", "primary_key": True},
                    {"name": "employee_id", "type": "INTEGER", "not_null": True, "fk": "employees.employee_id"},
                    {"name": "contact_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "relationship", "type": "VARCHAR(50)"},
                    {"name": "phone_primary", "type": "VARCHAR(20)"},
                    {"name": "phone_secondary", "type": "VARCHAR(20)"},
                    {"name": "email", "type": "VARCHAR(255)"},
                    {"name": "is_primary", "type": "BOOLEAN", "default": "false"},
                ],
            },
            {
                "name": "expense_reports",
                "columns": [
                    {"name": "report_id", "type": "SERIAL", "primary_key": True},
                    {"name": "employee_id", "type": "INTEGER", "not_null": True, "fk": "employees.employee_id"},
                    {"name": "report_title", "type": "VARCHAR(200)"},
                    {"name": "submission_date", "type": "DATE"},
                    {"name": "total_amount", "type": "DECIMAL(15,2)"},
                    {"name": "currency", "type": "VARCHAR(3)", "default": "'USD'"},
                    {"name": "status", "type": "VARCHAR(20)", "default": "'pending'"},
                    {"name": "approved_by", "type": "INTEGER", "fk": "employees.employee_id"},
                    {"name": "approved_date", "type": "DATE"},
                    {"name": "notes", "type": "TEXT"},
                ],
            },
            {
                "name": "expense_items",
                "columns": [
                    {"name": "item_id", "type": "SERIAL", "primary_key": True},
                    {"name": "report_id", "type": "INTEGER", "not_null": True, "fk": "expense_reports.report_id"},
                    {"name": "expense_date", "type": "DATE", "not_null": True},
                    {"name": "category", "type": "VARCHAR(50)"},
                    {"name": "description", "type": "VARCHAR(500)"},
                    {"name": "amount", "type": "DECIMAL(10,2)", "not_null": True},
                    {"name": "receipt_url", "type": "VARCHAR(500)"},
                    {"name": "is_billable", "type": "BOOLEAN", "default": "false"},
                ],
            },
            {
                "name": "org_announcements",
                "columns": [
                    {"name": "announcement_id", "type": "SERIAL", "primary_key": True},
                    {"name": "title", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "content", "type": "TEXT"},
                    {"name": "author_id", "type": "INTEGER", "fk": "employees.employee_id"},
                    {"name": "publish_date", "type": "TIMESTAMP"},
                    {"name": "expiry_date", "type": "TIMESTAMP"},
                    {"name": "priority", "type": "VARCHAR(20)", "default": "'normal'"},
                    {"name": "target_department_id", "type": "INTEGER", "fk": "departments.department_id"},
                    {"name": "is_pinned", "type": "BOOLEAN", "default": "false"},
                ],
            },
            {
                "name": "org_policies",
                "columns": [
                    {"name": "policy_id", "type": "SERIAL", "primary_key": True},
                    {"name": "policy_code", "type": "VARCHAR(50)", "unique": True},
                    {"name": "policy_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "category", "type": "VARCHAR(100)"},
                    {"name": "content", "type": "TEXT"},
                    {"name": "effective_date", "type": "DATE"},
                    {"name": "review_date", "type": "DATE"},
                    {"name": "version", "type": "VARCHAR(20)"},
                    {"name": "status", "type": "VARCHAR(20)", "default": "'active'"},
                ],
            },
        ],
    },
    # ═══════════════════════════════════════════════════════════════════════════
    # FINANCE & ACCOUNTING (30 tables)
    # ═══════════════════════════════════════════════════════════════════════════
    "finance": {
        "description": "Finance and Accounting",
        "tables": [
            {
                "name": "chart_of_accounts",
                "columns": [
                    {"name": "account_id", "type": "SERIAL", "primary_key": True},
                    {"name": "account_number", "type": "VARCHAR(20)", "not_null": True, "unique": True},
                    {"name": "account_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "account_type", "type": "VARCHAR(50)", "not_null": True},
                    {"name": "parent_account_id", "type": "INTEGER", "fk": "chart_of_accounts.account_id"},
                    {"name": "description", "type": "TEXT"},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                    {"name": "normal_balance", "type": "VARCHAR(10)"},
                ],
            },
            {
                "name": "fiscal_periods",
                "columns": [
                    {"name": "period_id", "type": "SERIAL", "primary_key": True},
                    {"name": "period_name", "type": "VARCHAR(50)", "not_null": True},
                    {"name": "fiscal_year", "type": "INTEGER", "not_null": True},
                    {"name": "period_number", "type": "INTEGER", "not_null": True},
                    {"name": "start_date", "type": "DATE", "not_null": True},
                    {"name": "end_date", "type": "DATE", "not_null": True},
                    {"name": "is_closed", "type": "BOOLEAN", "default": "false"},
                    {"name": "closed_date", "type": "DATE"},
                ],
            },
            {
                "name": "journal_entries",
                "columns": [
                    {"name": "entry_id", "type": "SERIAL", "primary_key": True},
                    {"name": "entry_number", "type": "VARCHAR(50)", "unique": True},
                    {"name": "entry_date", "type": "DATE", "not_null": True},
                    {"name": "period_id", "type": "INTEGER", "fk": "fiscal_periods.period_id"},
                    {"name": "description", "type": "TEXT"},
                    {"name": "source", "type": "VARCHAR(50)"},
                    {"name": "reference_number", "type": "VARCHAR(100)"},
                    {"name": "status", "type": "VARCHAR(20)", "default": "'draft'"},
                    {"name": "posted_by", "type": "INTEGER"},
                    {"name": "posted_date", "type": "TIMESTAMP"},
                ],
            },
            {
                "name": "journal_entry_lines",
                "columns": [
                    {"name": "line_id", "type": "SERIAL", "primary_key": True},
                    {"name": "entry_id", "type": "INTEGER", "not_null": True, "fk": "journal_entries.entry_id"},
                    {"name": "account_id", "type": "INTEGER", "not_null": True, "fk": "chart_of_accounts.account_id"},
                    {"name": "debit_amount", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "credit_amount", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "description", "type": "VARCHAR(500)"},
                    {"name": "cost_center", "type": "VARCHAR(50)"},
                ],
            },
            {
                "name": "vendors",
                "columns": [
                    {"name": "vendor_id", "type": "SERIAL", "primary_key": True},
                    {"name": "vendor_code", "type": "VARCHAR(50)", "unique": True},
                    {"name": "vendor_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "contact_name", "type": "VARCHAR(200)"},
                    {"name": "email", "type": "VARCHAR(255)"},
                    {"name": "phone", "type": "VARCHAR(20)"},
                    {"name": "address_line1", "type": "VARCHAR(255)"},
                    {"name": "city", "type": "VARCHAR(100)"},
                    {"name": "state", "type": "VARCHAR(100)"},
                    {"name": "postal_code", "type": "VARCHAR(20)"},
                    {"name": "country", "type": "VARCHAR(100)"},
                    {"name": "tax_id", "type": "VARCHAR(50)"},
                    {"name": "payment_terms", "type": "VARCHAR(50)"},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                ],
            },
            {
                "name": "invoices_payable",
                "columns": [
                    {"name": "invoice_id", "type": "SERIAL", "primary_key": True},
                    {"name": "invoice_number", "type": "VARCHAR(100)", "not_null": True},
                    {"name": "vendor_id", "type": "INTEGER", "not_null": True, "fk": "vendors.vendor_id"},
                    {"name": "invoice_date", "type": "DATE", "not_null": True},
                    {"name": "due_date", "type": "DATE"},
                    {"name": "total_amount", "type": "DECIMAL(15,2)", "not_null": True},
                    {"name": "tax_amount", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "currency", "type": "VARCHAR(3)", "default": "'USD'"},
                    {"name": "status", "type": "VARCHAR(20)", "default": "'pending'"},
                    {"name": "payment_date", "type": "DATE"},
                    {"name": "notes", "type": "TEXT"},
                ],
            },
            {
                "name": "invoice_payable_lines",
                "columns": [
                    {"name": "line_id", "type": "SERIAL", "primary_key": True},
                    {"name": "invoice_id", "type": "INTEGER", "not_null": True, "fk": "invoices_payable.invoice_id"},
                    {"name": "account_id", "type": "INTEGER", "fk": "chart_of_accounts.account_id"},
                    {"name": "description", "type": "VARCHAR(500)"},
                    {"name": "quantity", "type": "DECIMAL(10,2)", "default": "1"},
                    {"name": "unit_price", "type": "DECIMAL(15,4)"},
                    {"name": "amount", "type": "DECIMAL(15,2)", "not_null": True},
                    {"name": "cost_center", "type": "VARCHAR(50)"},
                ],
            },
            {
                "name": "vendor_payments",
                "columns": [
                    {"name": "payment_id", "type": "SERIAL", "primary_key": True},
                    {"name": "payment_number", "type": "VARCHAR(50)", "unique": True},
                    {"name": "vendor_id", "type": "INTEGER", "not_null": True, "fk": "vendors.vendor_id"},
                    {"name": "payment_date", "type": "DATE", "not_null": True},
                    {"name": "payment_method", "type": "VARCHAR(50)"},
                    {"name": "total_amount", "type": "DECIMAL(15,2)", "not_null": True},
                    {"name": "currency", "type": "VARCHAR(3)", "default": "'USD'"},
                    {"name": "bank_account_id", "type": "INTEGER", "fk": "bank_accounts.bank_account_id"},
                    {"name": "reference_number", "type": "VARCHAR(100)"},
                    {"name": "status", "type": "VARCHAR(20)", "default": "'completed'"},
                ],
            },
            {
                "name": "payment_allocations",
                "columns": [
                    {"name": "allocation_id", "type": "SERIAL", "primary_key": True},
                    {"name": "payment_id", "type": "INTEGER", "not_null": True, "fk": "vendor_payments.payment_id"},
                    {"name": "invoice_id", "type": "INTEGER", "not_null": True, "fk": "invoices_payable.invoice_id"},
                    {"name": "amount", "type": "DECIMAL(15,2)", "not_null": True},
                ],
            },
            {
                "name": "bank_accounts",
                "columns": [
                    {"name": "bank_account_id", "type": "SERIAL", "primary_key": True},
                    {"name": "account_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "account_number", "type": "VARCHAR(50)"},
                    {"name": "routing_number", "type": "VARCHAR(50)"},
                    {"name": "bank_name", "type": "VARCHAR(200)"},
                    {"name": "account_type", "type": "VARCHAR(50)"},
                    {"name": "currency", "type": "VARCHAR(3)", "default": "'USD'"},
                    {"name": "current_balance", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "gl_account_id", "type": "INTEGER", "fk": "chart_of_accounts.account_id"},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                ],
            },
            {
                "name": "bank_transactions",
                "columns": [
                    {"name": "transaction_id", "type": "SERIAL", "primary_key": True},
                    {"name": "bank_account_id", "type": "INTEGER", "not_null": True, "fk": "bank_accounts.bank_account_id"},
                    {"name": "transaction_date", "type": "DATE", "not_null": True},
                    {"name": "transaction_type", "type": "VARCHAR(50)"},
                    {"name": "amount", "type": "DECIMAL(15,2)", "not_null": True},
                    {"name": "description", "type": "VARCHAR(500)"},
                    {"name": "reference_number", "type": "VARCHAR(100)"},
                    {"name": "is_reconciled", "type": "BOOLEAN", "default": "false"},
                    {"name": "reconciled_date", "type": "DATE"},
                ],
            },
            {
                "name": "bank_reconciliations",
                "columns": [
                    {"name": "reconciliation_id", "type": "SERIAL", "primary_key": True},
                    {"name": "bank_account_id", "type": "INTEGER", "not_null": True, "fk": "bank_accounts.bank_account_id"},
                    {"name": "statement_date", "type": "DATE", "not_null": True},
                    {"name": "statement_balance", "type": "DECIMAL(15,2)", "not_null": True},
                    {"name": "book_balance", "type": "DECIMAL(15,2)"},
                    {"name": "difference", "type": "DECIMAL(15,2)"},
                    {"name": "status", "type": "VARCHAR(20)", "default": "'in_progress'"},
                    {"name": "completed_date", "type": "DATE"},
                ],
            },
            {
                "name": "budgets",
                "columns": [
                    {"name": "budget_id", "type": "SERIAL", "primary_key": True},
                    {"name": "budget_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "fiscal_year", "type": "INTEGER", "not_null": True},
                    {"name": "department_id", "type": "INTEGER"},
                    {"name": "status", "type": "VARCHAR(20)", "default": "'draft'"},
                    {"name": "approved_by", "type": "INTEGER"},
                    {"name": "approved_date", "type": "DATE"},
                    {"name": "notes", "type": "TEXT"},
                ],
            },
            {
                "name": "budget_lines",
                "columns": [
                    {"name": "budget_line_id", "type": "SERIAL", "primary_key": True},
                    {"name": "budget_id", "type": "INTEGER", "not_null": True, "fk": "budgets.budget_id"},
                    {"name": "account_id", "type": "INTEGER", "not_null": True, "fk": "chart_of_accounts.account_id"},
                    {"name": "period_id", "type": "INTEGER", "fk": "fiscal_periods.period_id"},
                    {"name": "budgeted_amount", "type": "DECIMAL(15,2)", "not_null": True},
                    {"name": "notes", "type": "TEXT"},
                ],
            },
            {
                "name": "fixed_assets",
                "columns": [
                    {"name": "asset_id", "type": "SERIAL", "primary_key": True},
                    {"name": "asset_tag", "type": "VARCHAR(50)", "unique": True},
                    {"name": "asset_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "category", "type": "VARCHAR(100)"},
                    {"name": "acquisition_date", "type": "DATE"},
                    {"name": "acquisition_cost", "type": "DECIMAL(15,2)"},
                    {"name": "useful_life_years", "type": "INTEGER"},
                    {"name": "salvage_value", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "depreciation_method", "type": "VARCHAR(50)"},
                    {"name": "accumulated_depreciation", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "current_value", "type": "DECIMAL(15,2)"},
                    {"name": "location", "type": "VARCHAR(200)"},
                    {"name": "status", "type": "VARCHAR(20)", "default": "'active'"},
                    {"name": "disposal_date", "type": "DATE"},
                ],
            },
            {
                "name": "depreciation_schedule",
                "columns": [
                    {"name": "schedule_id", "type": "SERIAL", "primary_key": True},
                    {"name": "asset_id", "type": "INTEGER", "not_null": True, "fk": "fixed_assets.asset_id"},
                    {"name": "period_id", "type": "INTEGER", "fk": "fiscal_periods.period_id"},
                    {"name": "depreciation_date", "type": "DATE", "not_null": True},
                    {"name": "depreciation_amount", "type": "DECIMAL(15,2)", "not_null": True},
                    {"name": "accumulated_total", "type": "DECIMAL(15,2)"},
                    {"name": "book_value", "type": "DECIMAL(15,2)"},
                    {"name": "is_posted", "type": "BOOLEAN", "default": "false"},
                ],
            },
            {
                "name": "tax_rates",
                "columns": [
                    {"name": "tax_rate_id", "type": "SERIAL", "primary_key": True},
                    {"name": "tax_code", "type": "VARCHAR(20)", "unique": True},
                    {"name": "tax_name", "type": "VARCHAR(100)", "not_null": True},
                    {"name": "rate_percentage", "type": "DECIMAL(6,4)", "not_null": True},
                    {"name": "tax_type", "type": "VARCHAR(50)"},
                    {"name": "jurisdiction", "type": "VARCHAR(100)"},
                    {"name": "effective_date", "type": "DATE"},
                    {"name": "end_date", "type": "DATE"},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                ],
            },
            {
                "name": "currencies",
                "columns": [
                    {"name": "currency_code", "type": "VARCHAR(3)", "primary_key": True},
                    {"name": "currency_name", "type": "VARCHAR(100)", "not_null": True},
                    {"name": "symbol", "type": "VARCHAR(10)"},
                    {"name": "decimal_places", "type": "INTEGER", "default": "2"},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                ],
            },
            {
                "name": "exchange_rates",
                "columns": [
                    {"name": "rate_id", "type": "SERIAL", "primary_key": True},
                    {"name": "from_currency", "type": "VARCHAR(3)", "not_null": True, "fk": "currencies.currency_code"},
                    {"name": "to_currency", "type": "VARCHAR(3)", "not_null": True, "fk": "currencies.currency_code"},
                    {"name": "rate_date", "type": "DATE", "not_null": True},
                    {"name": "exchange_rate", "type": "DECIMAL(18,8)", "not_null": True},
                    {"name": "source", "type": "VARCHAR(50)"},
                ],
            },
            {
                "name": "cost_centers",
                "columns": [
                    {"name": "cost_center_id", "type": "SERIAL", "primary_key": True},
                    {"name": "cost_center_code", "type": "VARCHAR(50)", "unique": True},
                    {"name": "cost_center_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "parent_id", "type": "INTEGER", "fk": "cost_centers.cost_center_id"},
                    {"name": "manager_id", "type": "INTEGER"},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                ],
            },
            {
                "name": "projects_financial",
                "columns": [
                    {"name": "project_id", "type": "SERIAL", "primary_key": True},
                    {"name": "project_code", "type": "VARCHAR(50)", "unique": True},
                    {"name": "project_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "client_id", "type": "INTEGER"},
                    {"name": "start_date", "type": "DATE"},
                    {"name": "end_date", "type": "DATE"},
                    {"name": "budgeted_amount", "type": "DECIMAL(15,2)"},
                    {"name": "actual_amount", "type": "DECIMAL(15,2)", "default": "0"},
                    {"name": "status", "type": "VARCHAR(20)", "default": "'active'"},
                    {"name": "billing_type", "type": "VARCHAR(50)"},
                ],
            },
            {
                "name": "project_costs",
                "columns": [
                    {"name": "cost_id", "type": "SERIAL", "primary_key": True},
                    {"name": "project_id", "type": "INTEGER", "not_null": True, "fk": "projects_financial.project_id"},
                    {"name": "cost_date", "type": "DATE", "not_null": True},
                    {"name": "cost_category", "type": "VARCHAR(100)"},
                    {"name": "description", "type": "VARCHAR(500)"},
                    {"name": "amount", "type": "DECIMAL(15,2)", "not_null": True},
                    {"name": "is_billable", "type": "BOOLEAN", "default": "true"},
                    {"name": "invoice_id", "type": "INTEGER"},
                ],
            },
            {
                "name": "audit_trail",
                "columns": [
                    {"name": "audit_id", "type": "SERIAL", "primary_key": True},
                    {"name": "table_name", "type": "VARCHAR(100)", "not_null": True},
                    {"name": "record_id", "type": "INTEGER"},
                    {"name": "action", "type": "VARCHAR(20)", "not_null": True},
                    {"name": "old_values", "type": "JSONB"},
                    {"name": "new_values", "type": "JSONB"},
                    {"name": "changed_by", "type": "INTEGER"},
                    {"name": "changed_at", "type": "TIMESTAMP", "default": "CURRENT_TIMESTAMP"},
                    {"name": "ip_address", "type": "VARCHAR(50)"},
                ],
            },
            {
                "name": "financial_reports",
                "columns": [
                    {"name": "report_id", "type": "SERIAL", "primary_key": True},
                    {"name": "report_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "report_type", "type": "VARCHAR(50)"},
                    {"name": "period_id", "type": "INTEGER", "fk": "fiscal_periods.period_id"},
                    {"name": "generated_date", "type": "TIMESTAMP"},
                    {"name": "generated_by", "type": "INTEGER"},
                    {"name": "parameters", "type": "JSONB"},
                    {"name": "file_path", "type": "VARCHAR(500)"},
                ],
            },
            {
                "name": "intercompany_accounts",
                "columns": [
                    {"name": "ic_account_id", "type": "SERIAL", "primary_key": True},
                    {"name": "entity_from", "type": "VARCHAR(100)", "not_null": True},
                    {"name": "entity_to", "type": "VARCHAR(100)", "not_null": True},
                    {"name": "gl_account_id", "type": "INTEGER", "fk": "chart_of_accounts.account_id"},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                ],
            },
            {
                "name": "intercompany_transactions",
                "columns": [
                    {"name": "ic_transaction_id", "type": "SERIAL", "primary_key": True},
                    {"name": "ic_account_id", "type": "INTEGER", "not_null": True, "fk": "intercompany_accounts.ic_account_id"},
                    {"name": "transaction_date", "type": "DATE", "not_null": True},
                    {"name": "amount", "type": "DECIMAL(15,2)", "not_null": True},
                    {"name": "description", "type": "VARCHAR(500)"},
                    {"name": "reference_number", "type": "VARCHAR(100)"},
                    {"name": "status", "type": "VARCHAR(20)", "default": "'pending'"},
                ],
            },
            {
                "name": "payment_terms",
                "columns": [
                    {"name": "term_id", "type": "SERIAL", "primary_key": True},
                    {"name": "term_code", "type": "VARCHAR(20)", "unique": True},
                    {"name": "term_name", "type": "VARCHAR(100)", "not_null": True},
                    {"name": "days_due", "type": "INTEGER"},
                    {"name": "discount_percentage", "type": "DECIMAL(5,2)", "default": "0"},
                    {"name": "discount_days", "type": "INTEGER"},
                    {"name": "description", "type": "TEXT"},
                ],
            },
            {
                "name": "credit_memos",
                "columns": [
                    {"name": "memo_id", "type": "SERIAL", "primary_key": True},
                    {"name": "memo_number", "type": "VARCHAR(50)", "unique": True},
                    {"name": "vendor_id", "type": "INTEGER", "fk": "vendors.vendor_id"},
                    {"name": "original_invoice_id", "type": "INTEGER", "fk": "invoices_payable.invoice_id"},
                    {"name": "memo_date", "type": "DATE", "not_null": True},
                    {"name": "amount", "type": "DECIMAL(15,2)", "not_null": True},
                    {"name": "reason", "type": "TEXT"},
                    {"name": "status", "type": "VARCHAR(20)", "default": "'open'"},
                ],
            },
            {
                "name": "recurring_entries",
                "columns": [
                    {"name": "recurring_id", "type": "SERIAL", "primary_key": True},
                    {"name": "entry_name", "type": "VARCHAR(200)", "not_null": True},
                    {"name": "frequency", "type": "VARCHAR(20)"},
                    {"name": "next_date", "type": "DATE"},
                    {"name": "end_date", "type": "DATE"},
                    {"name": "template_entry_id", "type": "INTEGER", "fk": "journal_entries.entry_id"},
                    {"name": "is_active", "type": "BOOLEAN", "default": "true"},
                    {"name": "last_generated", "type": "DATE"},
                ],
            },
        ],
    },
}

